force-app/main/default/objects/Assignment_Group__c/Assignment_Group__c.object-meta.xml
<CustomObject>
    <label>Assignment Group</label>
    <nameField>
        <label>Round Robin Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment_Group_Member__c/Assignment_Group_Member__c.object-meta.xml
<CustomObject>
    <label>Assignment Group Member</label>
    <nameField>
        <displayFormat>GM-{0000}</displayFormat>
        <label>Group Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Tracking__c/User_Tracking__c.object-meta.xml
<CustomObject>
    <label>User Tracking</label>
    <nameField>
        <displayFormat>UT-{0000}</displayFormat>
        <label>User Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Tracking__c/fields/Checkin_Detatime__c.field-meta.xml
<CustomField>
    <fullName>Checkin_Detatime__c</fullName>
    <label>Checkin Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Checkout_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Checkout_Datetime__c</fullName>
    <label>Checkout Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserTrackingTest.cls
@isTest
public class UserTrackingTest {

    
    @isTest
    public Static void Method1(){
        User_Tracking__c user = new User_Tracking__c();
        insert user;
    }

    @isTest
    public static void users()
    {
        test.startTest();
        
        User UserId = [SELECT Id,Name FROM User LIMIT 1 ];
        Assignment_Group__c grouping= new Assignment_Group__c();
        grouping.Name='Test';
        insert grouping;
        
        Assignment_Group_Member__c member=new Assignment_Group_Member__c();
        member.Group_Member__c=UserId.Id;   //
        member.Assignment_Group__c=grouping.Id;
        member.Assignment_Id__c=12;
        insert member;
            
        User_Tracking__c users=new User_Tracking__c();
        users.Checkin_Detatime__c=Date.today();
        users.Checkout_Datetime__c=Date.today();
        users.Member__c=UserId.Id; //
        insert users;
        
        UserTracking.OnpageLoad(UserId.Id);
        UserTracking.OnpageLoad(UserId.Id);
        //UserTracking.UserCheckin('0055g000002pmqhAAA');
        new UserTracking();        
        UserTracking.UserCheckin(UserId.Id);
        UserTracking.UserCheckout(UserId.Id);
        UserTracking.UserCheckout(UserId.Id);
        UserTracking.UserCheckout(null);
        test.stopTest();
    }
    
   
    @isTest
    public static void Method(){
        
        Profile p = [SELECT Id,Name FROM Profile LIMIT 1];
        System.debug('The Profile Name::'+p);
        User use = new User();
        use.Alias = 'Dines';               
        use.Username = 'dineshbaddwar@var.com';
        use.Email = 'dineshb@gmail.com';
        use.EmailEncodingKey = 'UTF-8';
        use.LastName = 'ondontecom';
        use.LanguageLocaleKey = 'en_US';
        use.LocaleSidKey = 'en_US';
        use.TimeZoneSidKey = 'America/Los_Angeles';
        use.ProfileId = p.Id;
        insert use;
          UserTracking.OnpageLoad(use.Id);
            UserTracking.UserCheckin(use.Id);
            UserTracking.UserCheckout(use.Id);
        System.debug('The User Details::'+use);
    }
    
   
    
}