force-app/main/default/objects/Assignment_Group__c/Assignment_Group__c.object-meta.xml
<CustomObject>
    <label>Assignment Group</label>
    <nameField>
        <label>Round Robin Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment_Group_Member__c/Assignment_Group_Member__c.object-meta.xml
<CustomObject>
    <label>Assignment Group Member</label>
    <nameField>
        <displayFormat>GM-{0000}</displayFormat>
        <label>Group Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment_Group_Member__c/fields/Out_Of_Office__c.field-meta.xml
<CustomField>
    <fullName>Out_Of_Office__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Out Of Office</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Audit_Counsellor__c/Audit_Counsellor__c.object-meta.xml
<CustomObject>
    <label>Audit Counsellor</label>
    <nameField>
        <displayFormat>AC - {000}</displayFormat>
        <label>Audit Officer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Counsellors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Counsellor__c/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>Audit_Officer__c</referenceTo>
    <relationshipLabel>Audit Counsellors</relationshipLabel>
    <relationshipName>Audit_Counsellors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Counsellor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>User__r.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Audit_Counsellor__c/fields/Last_RRid__c.field-meta.xml
<CustomField>
    <fullName>Last_RRid__c</fullName>
    <label>Allocation Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Audit_Counsellor__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Counsellors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Officer__c/Audit_Officer__c.object-meta.xml
<CustomObject>
    <label>Admission Officer</label>
    <nameField>
        <displayFormat>AO-{000}</displayFormat>
        <label>Audit Officer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admission Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Officer__c/fields/AO__c.field-meta.xml
<CustomField>
    <fullName>AO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AO</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Officers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Officer__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>$User.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Audit_Officer__c/fields/Last_RRid__c.field-meta.xml
<CustomField>
    <fullName>Last_RRid__c</fullName>
    <label>Last RRid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/AO__c.field-meta.xml
<CustomField>
    <fullName>AO__c</fullName>
    <formula>Owner:User.AO__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AO</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <formula>Owner:User.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Learner_Uid__c.field-meta.xml
<CustomField>
    <fullName>Learner_Uid__c</fullName>
    <defaultValue>&quot;CTI&quot;</defaultValue>
    <label>Learner Uid</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CounsellorsAssignmentModule.cls
public without sharing class CounsellorsAssignmentModule {
    public CounsellorsAssignmentModule() {

    }

    public static void counsellorAssignmentLogic(List<lead> leadListOwnerTobeChanged){

        Map<String, List<String>> mapofAOIdByACIdList = new Map<String, List<String>>();
        Map<String, Integer> mapofAOIdByLastRRID = new Map<String, Integer>();
        Map<String, String> QnameAndRRidToMemberIDMap = new Map<String, String>();

        List<Lead> leadListTobeUpdate = new list<lead>();
        List<Audit_Officer__c> QtoBeUpdated = new List<Audit_Officer__c>();
        system.debug('leadListOwnerTobeChanged::'+leadListOwnerTobeChanged);
        mapofAOIdByACIdList = makeCustomQueueNameToListOfUserId();
        system.debug('mapofAOIdByACIdList::'+mapofAOIdByACIdList);
        mapofAOIdByLastRRID = makeQNameToLastAssignedQmemberRRid();
        system.debug('mapofAOIdByLastRRID::'+mapofAOIdByLastRRID);
        QnameAndRRidToMemberIDMap = makeQnameAndRRidToMemberID();
        system.debug('QnameAndRRidToMemberIDMap::'+QnameAndRRidToMemberIDMap);
		list<LeadShare> leadShareList = new list<LeadShare>();

        for(Lead ld : leadListOwnerTobeChanged){
            Boolean isAssigned = false;
            Integer qMemberSize = 1;
            

                While (mapofAOIdByACIdList != null && qMemberSize != null && mapofAOIdByACIdList.get(ld.ownerId) != null && isAssigned == false && qMemberSize <= mapofAOIdByACIdList.get(ld.ownerId).size()){
                    Integer currentRRid, LastRRid;
                    String QnameAndRRid, qMemberID;
                    system.debug('qNameToLastAssignedQmemberRRid.get(groupName)-->'+mapofAOIdByLastRRID.get(ld.ownerId));
                    if (mapofAOIdByLastRRID.get(ld.ownerId) != null)
                        LastRRid = mapofAOIdByLastRRID.get(ld.ownerId);
                    System.debug('LastRRid-------+++++' + LastRRid);
                    if (LastRRid == null || LastRRid < 1){
                        mapofAOIdByLastRRID.remove(ld.ownerId);
                        mapofAOIdByLastRRID.put(ld.ownerId, 0);
                        currentRRid = 1;
                        System.debug('Inside 1  currentRRid' + currentRRid);
                    }
                    system.debug('LastRRid::' + LastRRid);
                    system.debug('makeCustomQueueNameToListOfUserId.get(groupName).size()::' + mapofAOIdByACIdList.get(ld.ownerId).size());
                    if (LastRRid < mapofAOIdByACIdList.get(ld.ownerId).size()){
                        currentRRid = LastRRid + 1;
                        System.debug('Inside 2  currentRRid' + currentRRid);
                    } else{
                        currentRRid = 1;
                        LastRRid = 0;
                        System.debug('Inside 3  currentRRid' + currentRRid);
                    }
                    system.debug('currentRRid::'+currentRRid);
                    QnameAndRRid = ld.ownerId + String.valueOf(currentRRid);
                    system.debug('QnameAndRRid::' + QnameAndRRid);
                    system.debug('QnameAndRRidToMemberIDMap::' + QnameAndRRidToMemberIDMap);
                    qMemberID = QnameAndRRidToMemberIDMap.get(QnameAndRRid);
                    System.debug('QnameAndRRid::' + QnameAndRRid);
                    System.debug('qMemberID::' + qMemberID);
                    boolean test = true;
                    if(test) {
                        system.debug('qMemberID-->'+qMemberID);
                        //qName,qMemberID,userIdbyLeadcount,ld.Learner_Uid__c,assignmentConditionSatisfied(true)
                        if (qMemberID != null){
                            LastRRid = LastRRid + 1;
                        system.debug('qNameToLastAssignedQmemberRRid-->'+mapofAOIdByLastRRID);
                        mapofAOIdByLastRRID.remove(ld.ownerId);
                        mapofAOIdByLastRRID.put(ld.ownerId, LastRRid);
                           
                            ld.ownerId = Id.valueOf(qMemberID);
                            isAssigned = true;
                            leadListTobeUpdate.add(ld);
                        }
                        system.debug('LastRRid-->'+LastRRid);
                        
                        System.debug('qNameToLastAssignedQmemberRRid::' + mapofAOIdByLastRRID);
                        qMemberSize++;
                        system.debug('qMemberSize::' + qMemberSize);
                    } else{
                        system.debug('LastRRid-->'+LastRRid);
                        LastRRid = LastRRid + 1;
                        system.debug('LastRRid-->'+LastRRid);
                        mapofAOIdByLastRRID.remove(ld.ownerId);
                        mapofAOIdByLastRRID.put(ld.ownerId, LastRRid);
                        System.debug('qNameToLastAssignedQmemberRRid::' + mapofAOIdByLastRRID);
                        qMemberSize++;
                    }
                }
        }

        if(!mapofAOIdByLastRRID.keySet().isEmpty()){
            List<Audit_Officer__c> updateQrIdToAO = new List<Audit_Officer__c>();
            updateQrIdToAO = [SELECT id,Last_RRid__c,AO__c from Audit_Officer__c where IsActive__c = true and AO__c IN: mapofAOIdByLastRRID.keySet()];
            system.debug('updateQrIdToAO::'+updateQrIdToAO);
            for(Audit_Officer__c Q: updateQrIdToAO)
            {
                Q.Last_RRid__c = mapofAOIdByLastRRID.get(Q.AO__c);
                QtoBeUpdated.add(q);
            }
        }
		system.debug('QtoBeUpdated::'+QtoBeUpdated);
        if(!QtoBeUpdated.isEmpty()){
            update QtoBeUpdated;
        }
        system.debug('leadListTobeUpdate::'+leadListTobeUpdate);
        if(!leadListTobeUpdate.isEmpty()){
            update leadListTobeUpdate;
            //insert leadShareList;
        }

    }

    public static Map<String, List<String>> makeCustomQueueNameToListOfUserId(){
        
        List<Audit_Counsellor__c> auditCounsellorList = [select id,Audit_Officer__c,IsActive__c,Last_RRid__c,User__c,Audit_Officer__r.AO__c
                                                            from Audit_Counsellor__c
                                                            where IsActive__c = true And Available__c = true and Audit_Officer__c != null];
        
        
        
        Map<String, List<String>> customQueueNameToListOfUserId = new Map<String, List<String>>();
        List<Assignment_Group_Member__c> listOfExistingQueueMembers = new List<Assignment_Group_Member__c>();
        
        /*listOfExistingQueueMembers = [select id, name, Out_Of_Office__c, Assignment_Group__c, Assignment_Group__r.name, Assignment_Id__c, Leave_End_Date__c, Leave_Start_Date__c, Group_Member__c, Group_Member__r.Id
                                      from Assignment_Group_Member__c
                                      where Assignment_Group__r.name = :assignmentGroupName ANd Active__c = true ];*/
        system.debug('listOfExistingQueueMembers-->'+listOfExistingQueueMembers);
        if (!auditCounsellorList.isEmpty()){
            for (Audit_Counsellor__c counsellor : auditCounsellorList){
                if (customQueueNameToListOfUserId.containsKey(counsellor.Audit_Officer__r.AO__c)){
                    customQueueNameToListOfUserId.get(counsellor.Audit_Officer__r.AO__c).add(counsellor.User__c);
                } else{
                    customQueueNameToListOfUserId.put(counsellor.Audit_Officer__r.AO__c, new list<string>{ counsellor.User__c});
                }
            }
        }
        system.debug('customQueueNameToListOfUserId::' + customQueueNameToListOfUserId);
        return customQueueNameToListOfUserId;
    }

    public static Map<String, Integer> makeQNameToLastAssignedQmemberRRid(){
        Map<String, Integer> qNameToLastAssignedQmemberRRid 		= new Map<String, Integer>();
        List<Audit_Officer__c> existingAuditRec 					= new List<Audit_Officer__c>([SELECT id,Last_RRid__c,AO__c from Audit_Officer__c where IsActive__c = true]);
        
        for(Audit_Officer__c q: existingAuditRec)
        {
            if(q.Last_RRid__c != null)
            {
                qNameToLastAssignedQmemberRRid.put(q.AO__c, Integer.valueOf(q.Last_RRid__c));    
            }
            else 
                qNameToLastAssignedQmemberRRid.put(q.AO__c, null);
        }
        return qNameToLastAssignedQmemberRRid;
    }

    public static Map<String, String> makeQnameAndRRidToMemberID(){
        //Map<String, Map<String, Integer>> qNameAndMemberIdTORoundRobinIDMaP = new Map<String, Map<String, Integer>>();
        Map<String, String> QnameAndRRidToMemberIDMap = new Map<String, String>();
        list<Assignment_Group_Member__c> agmList = new list<Assignment_Group_Member__c>();
        
        List<Audit_Counsellor__c> auditCounsellorList = [select id,Audit_Officer__c,IsActive__c,Last_RRid__c,User__c,Audit_Officer__r.AO__c
                                                            from Audit_Counsellor__c
                                                            where IsActive__c = true ANd Available__c = true and Audit_Officer__c != null];
        system.debug('agmList::' + auditCounsellorList);
        if (!auditCounsellorList.isEmpty()){
            for (Audit_Counsellor__c agm : auditCounsellorList){
                String qName = agm.Audit_Officer__r.AO__c;
                String qMember = string.valueOf(agm.Last_RRid__c);
                system.debug('qName::' + qName);
                system.debug('qMember::' + qMember);
                if (!string.isBlank(qName) && !String.isBlank(qMember)){
                    String qNameAndQmamber = qName + qMember;
                    system.debug('qNameAndQmamber::' + qNameAndQmamber);
                    QnameAndRRidToMemberIDMap.put(qNameAndQmamber, String.valueOf(agm.User__c));
                }
            }
        }
        
        System.debug('QnameAndRRidToMemberIDMap---'+QnameAndRRidToMemberIDMap);
        return QnameAndRRidToMemberIDMap;
    }
}