force-app/main/default/objects/AO_Availability__c/AO_Availability__c.object-meta.xml
<CustomObject>
    <label>AO Availability</label>
    <nameField>
        <displayFormat>AOA - {000}</displayFormat>
        <label>AO Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Availabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Availability__c/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>Audit_Officer__c</referenceTo>
    <relationshipLabel>AO Availabilities</relationshipLabel>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Audited_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audited_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audited Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Checkin_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Checkin_DateTime__c</fullName>
    <label>Checkin DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Checkout_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Checkout_DateTime__c</fullName>
    <label>Checkout DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <formula>DATETIMEVALUE(CreatedDate )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Ideal_TIme__c.field-meta.xml
<CustomField>
    <fullName>Ideal_TIme__c</fullName>
    <formula>(NOW() -  Last_Engagement_Time__c )*24*60*60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ideal TIme</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Url__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url__c</fullName>
    <label>Meeting Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Onbehalf_AO__c.field-meta.xml
<CustomField>
    <fullName>Onbehalf_AO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Onbehalf AO</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AO_Availabilities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Meeting</fullName>
            </value>
            <value>
                <fullName>On Break</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Total_Idle_Time__c.field-meta.xml
<CustomField>
    <fullName>Total_Idle_Time__c</fullName>
    <label>Total Idle Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/User_Tracking__c.field-meta.xml
<CustomField>
    <fullName>User_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Tracking</label>
    <referenceTo>User_Tracking__c</referenceTo>
    <relationshipLabel>AO Availabilities</relationshipLabel>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assignment_Group_Member__c/Assignment_Group_Member__c.object-meta.xml
<CustomObject>
    <label>Assignment Group Member</label>
    <nameField>
        <displayFormat>GM-{0000}</displayFormat>
        <label>Group Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment_Group_Member__c/fields/Out_Of_Office__c.field-meta.xml
<CustomField>
    <fullName>Out_Of_Office__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Out Of Office</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Audit_Counsellor__c/Audit_Counsellor__c.object-meta.xml
<CustomObject>
    <label>Audit Counsellor</label>
    <nameField>
        <displayFormat>AC - {000}</displayFormat>
        <label>Audit Officer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Counsellors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Counsellor__c/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>Audit_Officer__c</referenceTo>
    <relationshipLabel>Audit Counsellors</relationshipLabel>
    <relationshipName>Audit_Counsellors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Counsellor__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>User__r.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Audit_Counsellor__c/fields/Last_RRid__c.field-meta.xml
<CustomField>
    <fullName>Last_RRid__c</fullName>
    <label>Allocation Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Audit_Counsellor__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Counsellors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Officer__c/Audit_Officer__c.object-meta.xml
<CustomObject>
    <label>Admission Officer</label>
    <nameField>
        <displayFormat>AO-{000}</displayFormat>
        <label>Audit Officer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admission Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Officer__c/fields/AO__c.field-meta.xml
<CustomField>
    <fullName>AO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AO</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Officers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Officer__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>$User.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Audit_Officer__c/fields/Last_RRid__c.field-meta.xml
<CustomField>
    <fullName>Last_RRid__c</fullName>
    <label>Last RRid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/User_Tracking__c.object-meta.xml
<CustomObject>
    <label>User Tracking</label>
    <nameField>
        <displayFormat>UT-{0000}</displayFormat>
        <label>User Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Tracking__c/fields/Check_in_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_in_Date__c</fullName>
    <formula>DATEVALUE( Checkin_Detatime__c+ 30/1440)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Check in Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Checkin_Detatime__c.field-meta.xml
<CustomField>
    <fullName>Checkin_Detatime__c</fullName>
    <label>Checkin Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Checkout_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Checkout_Datetime__c</fullName>
    <label>Checkout Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <formula>TEXT(Month( DATEVALUE(CreatedDate ) ))&amp;&quot;/&quot;&amp; TEXT(Day( DATEVALUE(CreatedDate ) )) &amp; &quot;/&quot; &amp; TEXT(Year( DATEVALUE(CreatedDate ) )) &amp; &quot; &quot; &amp; MID(TEXT(CreatedDate +330/1440 ),12,8)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserTracking.cls
public without sharing class UserTracking{
    public UserTracking(){
    }

    
    @AuraEnabled
    public static UserTrack OnpageLoad(string userId){
        UserTrack usr = new UserTrack();
        try{
            String LoggedInUser = UserInfo.getUserId();
            list<Audit_Counsellor__c> auditCounsellorListTOUpdate = new list<Audit_Counsellor__c>();

            System.debug('LoggedInUser =====> ' + LoggedInUser);
            list<User_Tracking__c> userTracking = [select id, Checkin_Detatime__c, Checkout_Datetime__c, Member__c
                                                   from User_Tracking__c
                                                   where Member__c = :userId and CreatedDate = TODAY
                                                   limit 1];
            List<Audit_Officer__c> AuditOfficer = [SELECT AO__c, Id, IsActive__c, Name
                                                   FROM Audit_Officer__c
                                                   Where AO__c = :LoggedInUser];
            List<AO_Availability__c> AOAvailablity = [SELECT Audited_Officer__c, Audit_Officer__c, Id, Ideal_TIme__c, Meeting_Url__c, Status__c
                                                      FROM AO_Availability__c
                                                      Where Audited_Officer__c = :LoggedInUser And CreatedDate = TODAY];
            list<Audit_Counsellor__c> auditCounsellorList = [Select Id, Available__c
                                                             From Audit_Counsellor__c
                                                             where User__c = :userId];
            if (!auditCounsellorList.isEmpty()){
                for (Audit_Counsellor__c acRec : auditCounsellorList){
                    Audit_Counsellor__c acRecToUpdate = new Audit_Counsellor__c();
                    acRecToUpdate.Id = acRec.Id;
                    acRecToUpdate.Available__c = true;
                    auditCounsellorListTOUpdate.add(acRecToUpdate);
                }
                if (!auditCounsellorListTOUpdate.isEmpty()){
                    update auditCounsellorListTOUpdate;
                }
            }
            if (!AOAvailablity.isEmpty()){
                usr.AOAvailableStatus = AOAvailablity[0].Status__c;
            } else{
                AO_Availability__c emptyAOAvail = new AO_Availability__c();
                emptyAOAvail.status__c = '';
                usr.AOAvailableStatus = emptyAOAvail.Status__c;
            }

            System.debug('AuditOfficer =======> ' + AuditOfficer);
            if (!AuditOfficer.isEmpty()){
                if (AuditOfficer[0].IsActive__c == true){
                    usr.LoggedInAuditOfficer = AuditOfficer[0];
                }
            } else{
                Audit_Officer__c AO = new Audit_Officer__c();
                usr.LoggedInAuditOfficer = AO;
            }

            if (!userTracking.isEmpty()){
                //if(System.now().time() > Time.newInstance(14, 45, 00, 00))
                usr.checkin = true;
                if (userTracking[0].Checkout_Datetime__c != null){
                    System.debug('checkout ===> ');
                    usr.checkout = true;

                } else{
                    System.debug('checkout in this ===> ');
                    usr.checkout = false;
                    UserTriggerHelper.enbaleAOOnLogin(userId);
                }

            } else{
                usr.checkin = false;
                usr.checkout = true;
            }

        } catch (Exception e){
            System.debug('stack trace ======> ' + e.getStackTraceString());
        }


        return usr;
    }

    @AuraEnabled
    public static UserTrackWrapperAfterCheckin UserCheckin(string userId){
        /*if(System.now().time() < Time.newInstance(08, 59, 00, 00)){

         }else{}*/

        UserTrackWrapperAfterCheckin UserTrackWrap = new UserTrackWrapperAfterCheckin();
        String eventStatus = 'Something went wrong';
        string groupName = '';
        DateTime dt = DateTime.now();
        String dayOfWeek = dt.format('EEEE');
        if (boolean.valueOf(system.label.Enable_Sunday_Checkin)){
            if (dayOfWeek == 'Sunday'){
                eventStatus = 'You can not checkin on Sundayr.';
                //return eventStatus;
            }
        }


        if (System.now().time() < Time.newInstance(08, 59, 00, 00)){
            eventStatus = 'You can not checkin before 9:00 AM.';
            //return eventStatus;
        }

        map<string, string> mapofGroupNameBySourceIntent = new map<string, string>();
        if (userId != null){
            list<User_Tracking__c> userTracking = new list<User_Tracking__c>();
            list<Assignment_Group_Member__c> agmList = new list<Assignment_Group_Member__c>();
            /*List<AO_Availability__c> AO_AvailabilityList = new List<AO_Availability__c>();

            AO_AvailabilityList = [Select Id
                                   From AO_Availability__c
                                   where Onbehalf_AO__c = :userId and Created_Date__c = today and Status__c != 'Not Available'];

            if (!AO_AvailabilityList.isEmpty()){
                eventStatus = 'Your Manager has already logged in.';
            }
*/
            userTracking = [select id, Checkin_Detatime__c, Checkout_Datetime__c, Member__c
                            from User_Tracking__c
                            where Member__c = :userId and CreatedDate = TODAY
                            limit 1];
            agmList = [select id, Group_Member__c, Assignment_Group__r.name
                       from Assignment_Group_Member__c
                       where Group_Member__c = :userId];
            List<Audit_Officer__c> AuditOfficer = [SELECT AO__c, Id, IsActive__c, Name
                                                   FROM Audit_Officer__c
                                                   Where AO__c = :userId];
            System.debug('AuditOfficer =======> ' + AuditOfficer);
            if (!AuditOfficer.isEmpty()){
                if (AuditOfficer[0].IsActive__c == true){
                    Audit_Counsellor__c AC = new Audit_Counsellor__c();
                    UserTrackWrap.AuditOfficerDetails = AuditOfficer[0];
                    UserTrackWrap.AuditcounsellorDetails = AC;
                }
            } else{
                list<Audit_Counsellor__c> AuditCounsellorlist = [SELECT Audit_Officer__c, Id, IsActive__c, Last_RRid__c, Name, User__c, Available__c
                                                                 FROM Audit_Counsellor__c
                                                                 where User__c = :userId and Available__c = false];

                if (!AuditCounsellorlist.isEmpty()){
                    for (Audit_Counsellor__c ac : AuditCounsellorlist){
                        ac.available__c = true;
                    }

                    update AuditCounsellorlist;
                }
                if (!AuditCounsellorlist.isEmpty()){
                    Audit_Officer__c AO = new Audit_Officer__c();
                    UserTrackWrap.AuditOfficerDetails = AO;
                    UserTrackWrap.AuditcounsellorDetails = AuditCounsellorlist[0];
                } else{
                    Audit_Officer__c AO = new Audit_Officer__c();
                    Audit_Counsellor__c AC = new Audit_Counsellor__c();
                    UserTrackWrap.AuditOfficerDetails = AO;
                    UserTrackWrap.AuditcounsellorDetails = AC;
                }

            }


            if (userTracking.isEmpty()){
                list<Source_Intent_And_Group_Name__mdt> groupNameSourceIntent = [select id, Group_Name__c, Source_Intent__c
                                                                                 from Source_Intent_And_Group_Name__mdt];

                if (!groupNameSourceIntent.isEmpty()){
                    for (Source_Intent_And_Group_Name__mdt signMeta : groupNameSourceIntent){
                        mapofGroupNameBySourceIntent.put(signMeta.Group_Name__c, signMeta.Source_Intent__c);
                    }
                }

                User_Tracking__c userTrackRec = new User_Tracking__c();
                userTrackRec.Member__c = userId;
                userTrackRec.Checkin_Detatime__c = DateTime.now();
                //insert userTrackRec;
                if (boolean.valueOf(system.label.leadAssignmentOnChecking)){

                    if (!agmList.isEmpty()){
                        for (Assignment_Group_Member__c agm : agmList){
                            agm.Out_Of_Office__c = false;

                        }

                        update agmList;
                        for (Assignment_Group_Member__c agm : agmList){
                            RoundRobinLeadAssignment.assignLeadsToBDS(mapofGroupNameBySourceIntent.get(agm.Assignment_Group__r.name));
                        }

                    }
                }
                if (!AuditOfficer.isEmpty()){
                    if (AuditOfficer[0].IsActive__c == true){
                        String usertrackStatus = SMMeetingLinkGenerator.MeetingUrlGenerator(userId, userTrackRec);
                    }
                    // if (usertrackStatus == 'User Track Record Created Successfully') {

                    // }
                } else{
                    insert userTrackRec;
                }
                eventStatus = 'Checkin successful';
            } else{
                eventStatus = 'Your checkin was already created.';
            }

        } else{
            eventStatus = 'User is not registered in system.Please contact to your admin.';
        }
        UserTrackWrap.eventStatus = eventStatus;
        return UserTrackWrap;
    }

    @AuraEnabled
    public static String UserCheckout(string userId){
        String eventStatus = 'Something went wrong';
        list<Audit_Counsellor__c> auditCounsellorListTOUpdate = new list<Audit_Counsellor__c>();

        if (userId != null){
            list<User_Tracking__c> userTracking = new list<User_Tracking__c>();
            list<Assignment_Group_Member__c> agmList = new list<Assignment_Group_Member__c>();
            list<Audit_Counsellor__c> auditCounsellorList = [Select Id, Available__c
                                                             From Audit_Counsellor__c
                                                             where User__c = :userId];
            if (!auditCounsellorList.isEmpty()){
                for (Audit_Counsellor__c acRec : auditCounsellorList){
                    Audit_Counsellor__c acRecToUpdate = new Audit_Counsellor__c();
                    acRecToUpdate.Id = acRec.Id;
                    acRecToUpdate.Available__c = false;
                    auditCounsellorListTOUpdate.add(acRecToUpdate);
                }
                if (!auditCounsellorListTOUpdate.isEmpty()){
                    update auditCounsellorListTOUpdate;
                }
            }
            List<AO_Availability__c> AO_OnBreak = [SELECT Audited_Officer__c, Checkin_DateTime__c, Checkout_DateTime__c, Id, Meeting_Unique_Id__c, Meeting_Url__c, Name, Status__c, Total_Idle_Time__c
                                                   FROM AO_Availability__c
                                                   Where Audited_Officer__c = :userId and CreatedDate = Today];
            userTracking = [select id, Checkin_Detatime__c, Checkout_Datetime__c, Member__c
                            from User_Tracking__c
                            where Member__c = :userId and createddate = TODAY
                            limit 1];
            agmList = [select id, Group_Member__c
                       from Assignment_Group_Member__c
                       where Group_Member__c = :userId];
            if (!userTracking.isEmpty()){
                for (User_Tracking__c ut : userTracking){
                    ut.Checkout_Datetime__c = DateTime.now();
                }
                update userTracking;
                //Database.SaveResult[] srList = Database.insert(userTracking, false);
                if (userTracking[0].Checkin_Detatime__c != null && !AO_OnBreak.isEmpty()){
                    AO_OnBreak[0].status__c = 'Not Available';
                    AO_OnBreak[0].Checkout_DateTime__c = DateTime.now();
                    update AO_OnBreak[0];
                }
                if (!agmList.isEmpty()){
                    for (Assignment_Group_Member__c agm : agmList){
                        agm.Out_Of_Office__c = true;
                    }

                    update agmList;
                }

                eventStatus = 'Checkout datetime has been updated.';
            } else{
                eventStatus = 'You can not checkout without checkin.';
            }

        } else{
            eventStatus = 'User is not registered in system.Please contact to your admin.';
        }


        return eventStatus;
    }

    @AuraEnabled
    public static String BreakTime(string userId, string buttonlabel){
        System.debug('userId ======> ' + userId);
        System.debug('buttonlabel ======> ' + buttonlabel);
        string Message = '';
        try{
            List<AO_Availability__c> AO_OnBreak = [SELECT Audited_Officer__c, Checkin_DateTime__c, Checkout_DateTime__c, Id, Meeting_Unique_Id__c, Meeting_Url__c, Name, Status__c, Total_Idle_Time__c
                                                   FROM AO_Availability__c
                                                   Where Audited_Officer__c = :userId and CreatedDate = Today];

            if (!AO_OnBreak.isEmpty()){
                if (buttonlabel == 'Start Break Time' && AO_OnBreak[0].Status__c == 'In Meeting'){
                    Message = 'Please fill out Interview Feedback before marking yourself on Break!!!';
                } else if (buttonlabel == 'Start Break Time'){
                    AO_OnBreak[0].Status__c = 'On Break';
                    AO_OnBreak[0].Break_Start_Time__c = System.now();
                    Message = 'Break Time Started';
                    System.debug('AO_OnBreak[0] =====> ' + AO_OnBreak[0]);
                    update AO_OnBreak[0];
                    /*User_tracking__c userTrackingRec = new User_tracking__c();
                    userTrackingRec.Id = [Select Id
                                          From User_tracking__c
                                          Where Member__c = :userId and Check_in_Date__c = today].Id;
                    userTrackingRec.On_Break__c = 'yes';
                    update userTrackingRec;*/
                } else if (buttonlabel == 'End Break Time'){
                    AO_OnBreak[0].Status__c = 'Available';
                    AO_OnBreak[0].Break_End_Time__c = System.now();
                    Message = 'Break Time Ended';
                    System.debug('AO_OnBreak[0] =====> ' + AO_OnBreak[0]);
                    update AO_OnBreak[0];
                   /* User_tracking__c userTrackingRec = new User_tracking__c();
                    userTrackingRec.Id = [Select Id
                                          From User_tracking__c
                                          Where Member__c = :userId and Check_in_Date__c = today].Id;
                    userTrackingRec.On_Break__c = 'No';
                    update userTrackingRec;*/
                }

            }

        } catch (Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        return Message;
    }

    @AuraEnabled
    public static String MeetingStarted(string userId, string buttonlabel){
        string Message = '';
        try{
            List<AO_Availability__c> AO_OnBreak = [SELECT Audited_Officer__c, Checkin_DateTime__c, Checkout_DateTime__c, Id, Meeting_Unique_Id__c, Meeting_Url__c, Name, Status__c, Total_Idle_Time__c
                                                   FROM AO_Availability__c
                                                   Where Audited_Officer__c = :userId and CreatedDate = Today];
            System.debug('AO_OnBreak =====> ' + AO_OnBreak);
            if (!AO_OnBreak.isEmpty()){
                if (buttonlabel == 'Start Meeting'){
                    AO_OnBreak[0].Status__c = 'In Meeting';
                    Message = 'Meeting is Started';
                } else if (buttonlabel == 'End Meeting'){
                    AO_OnBreak[0].Status__c = 'Available';
                    Message = 'Meeting is Ended';
                }
                System.debug('AO_OnBreak[0] =====> ' + AO_OnBreak[0]);
                update AO_OnBreak[0];
            }
        } catch (Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        return Message;
    }

    public class UserTrack{
        @AuraEnabled
        public boolean checkin;
        @AuraEnabled
        public boolean checkout;
        @AuraEnabled
        public Audit_Officer__c LoggedInAuditOfficer;
        @AuraEnabled
        public String AOAvailableStatus;
    }

    public class UserTrackWrapperAfterCheckin{
        @AuraEnabled
        public String eventStatus;
        @AuraEnabled
        public Audit_Officer__c AuditOfficerDetails;
        @AuraEnabled
        public Audit_Counsellor__c AuditcounsellorDetails;

    }

}