force-app/main/default/objects/AO_Availability__c/AO_Availability__c.object-meta.xml
<CustomObject>
    <label>AO Availability</label>
    <nameField>
        <displayFormat>AOA - {000}</displayFormat>
        <label>AO Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Availabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Availability__c/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>Audit_Officer__c</referenceTo>
    <relationshipLabel>AO Availabilities</relationshipLabel>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Audited_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audited_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audited Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Url__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url__c</fullName>
    <label>Meeting Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Meeting</fullName>
            </value>
            <value>
                <fullName>On Break</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/AO_Interview_Status_Manual__c.field-meta.xml
<CustomField>
    <fullName>AO_Interview_Status_Manual__c</fullName>
    <label>AO Interview Status (Manual)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Communication__c.field-meta.xml
<CustomField>
    <fullName>Communication__c</fullName>
    <label>Communication</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Financials__c.field-meta.xml
<CustomField>
    <fullName>Financials__c</fullName>
    <label>Financials</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Intent__c.field-meta.xml
<CustomField>
    <fullName>Intent__c</fullName>
    <label>Intent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interview_Feedback_Notes_AO__c.field-meta.xml
<CustomField>
    <fullName>Interview_Feedback_Notes_AO__c</fullName>
    <label>Interview Feedback Notes (AO)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interviewer_Name__c.field-meta.xml
<CustomField>
    <fullName>Interviewer_Name__c</fullName>
    <formula>Interviewer__r.FirstName+&quot; &quot;+Interviewer__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interviewer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Lead_Version__c.field-meta.xml
<CustomField>
    <fullName>Lead_Version__c</fullName>
    <formula>Text(Lead__r.Lead_Version__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Version</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Relevel_Interview_Id__c.field-meta.xml
<CustomField>
    <fullName>Relevel_Interview_Id__c</fullName>
    <label>Relevel Interview Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Interviewer Not Found</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Interviewer Missed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
                <isActive>false</isActive>
                <label>Disqualified</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <isActive>false</isActive>
                <label>Qualified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Admission_Letter_Sent__c.field-meta.xml
<CustomField>
    <fullName>Admission_Letter_Sent__c</fullName>
    <label>Send Admission Letter - NA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <isActive>false</isActive>
                <label>On Hold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/AO_Interview_Status_Manual__c.field-meta.xml
<CustomField>
    <fullName>AO_Interview_Status_Manual__c</fullName>
    <label>AO Interview Status (Manual)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Learner No-Show</fullName>
            </value>
            <value>
                <fullName>AO No-Show</fullName>
            </value>
            <value>
                <fullName>Conducted</fullName>
            </value>
            <value>
                <fullName>Joined &amp; Dropped</fullName>
                <isActive>false</isActive>
                <label>Joined &amp; Dropped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Book_Later_Flow__c.field-meta.xml
<CustomField>
    <fullName>Book_Later_Flow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Book Later Flow Missed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Communication__c.field-meta.xml
<CustomField>
    <fullName>Communication__c</fullName>
    <label>Communication</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Financials__c.field-meta.xml
<CustomField>
    <fullName>Financials__c</fullName>
    <label>Financials</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Intent__c.field-meta.xml
<CustomField>
    <fullName>Intent__c</fullName>
    <label>Intent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Interview_Feedback_Notes_AO__c.field-meta.xml
<CustomField>
    <fullName>Interview_Feedback_Notes_AO__c</fullName>
    <label>Interview Feedback Notes (AO)</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Interview_Id__c.field-meta.xml
<CustomField>
    <fullName>Interview_Id__c</fullName>
    <label>Interview Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Interview_Request_Generated__c.field-meta.xml
<CustomField>
    <fullName>Interview_Request_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Interview Request Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
            <value>
                <fullName>Conducted</fullName>
            </value>
            <value>
                <fullName>Offer Rolled Out</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Called</fullName>
            </value>
            <value>
                <fullName>Nurturing</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Version__c.field-meta.xml
<CustomField>
    <fullName>Lead_Version__c</fullName>
    <label>Lead Version</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V0</fullName>
            </value>
            <value>
                <fullName>V1</fullName>
                <default>true</default>
                <label>V1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Relevance_Experience__c.field-meta.xml
<CustomField>
    <fullName>Relevance_Experience__c</fullName>
    <label>Relevance Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/API_UpsertMultipleLeadInterview.cls
@RestResource(urlMapping = '/inteview_mapping/*')
global without sharing class API_UpsertMultipleLeadInterview{
    @httpPost
    global static responseWrapper LeadInterviewCreation(){
        List<Interview__c> interviewList = new List<Interview__c>();
        responseWrapper response = new responseWrapper();
        
        API_UpsertMultipleLeadInterviewWrapper interviewDetails_relevel = API_UpsertMultipleLeadInterviewWrapper.parse(RestContext.request.requestBody.tostring());
        
        string respo = Utility.getAoDetails(interviewDetails_relevel.lead_id, interviewDetails_relevel.relevel_interview_id);
        
        system.debug('respo-->'+respo);
        
        if(respo == 'success'){
            AO_Availability__c aoDetails = AOAvalibilityModule.fetchAvailableAO();
            
            try{
                if ( aoDetails == null ){
                    response.message = 'User Not Found';
                    response.status_code = '404';
                    response.relevel_interview_id = interviewDetails_relevel.relevel_interview_id;
                    response.LeadId = interviewDetails_relevel.lead_id;
                    Lead ld = new lead();
                    ld.Interview_Request_Generated__c = true;
                    ld.Id = interviewDetails_relevel.lead_id;
                    update ld;
                }
                else{
                    if (interviewDetails_relevel.lead_id != null){
                        Lead Ld = new Lead();
                        ld.Interview_Id__c = interviewDetails_relevel.relevel_interview_id;
                        Ld.Id = interviewDetails_relevel.lead_id;
                        Ld.Lead_Version__c = 'V1';
                        ld.OwnerId = aoDetails.Audited_Officer__c;
                        ld.Audit_Officer__c = aoDetails.Audited_Officer__c;
                        ld.Lead_Stage__c = 'Unassigned';
                        ld.Intent__c = null;
                        ld.Communication__c = null;
                        ld.Financials__c = null;
                        ld.AO_Interview_Status_Manual__c = null;
                        ld.Relevance_Experience__c = null;
                        ld.Interview_Feedback_Notes_AO__c = null;
                        ld.Admission_Letter_Sent__c = null;
                        ld.Book_Later_Flow__c = false;
                        ld.Interview_Request_Generated__c = true;
                        update Ld;
                    }
                    Interview__c interviewRec = new Interview__c();
                    interviewRec.Lead__c = interviewDetails_relevel.lead_id;
                    interviewRec.Relevel_Interview_Id__c = interviewDetails_relevel.relevel_interview_id;
                    interviewRec.Interviewer__c = aoDetails.Audited_Officer__c;
                    interviewRec.Active__c = true;
                    interviewRec.Meeting_URL__c = aoDetails.Meeting_Url__c;
                    interviewRec.Meeting_Unique_Id__c = aoDetails.Meeting_Unique_Id__c;
                    interviewRec.OwnerId = aoDetails.Audited_Officer__c;
                    if ( aoDetails == null ){
                        interviewRec.Status__c = 'Interviewer Not Found';
                    }
                    else{
                        interviewRec.Status__c = 'Started';
                    }
                    Database.SaveResult successRespo = Database.insert ( interviewRec, false );
                    System.debug('successRespo =====> ' + successRespo);
                    if ( successRespo.isSuccess() ){
                        Interview__c interviewRecordInserted = [Select Id, Interviewer__c, Interviewer_Name__c, Interviewer_Email__c, Lead__c, Meeting_URL__c, Relevel_Interview_Id__c, Status__c
                                                                From Interview__c
                                                                where Id = :successRespo.getId()];
                        
                        response.interviewer_id = interviewRecordInserted.Interviewer__c;
                        response.interviewer_name = interviewRecordInserted.Interviewer_Name__c;
                        response.interviewer_email = interviewRecordInserted.Interviewer_Email__c;
                        response.meeting_url = aoDetails.Meeting_Url__c;
                        response.relevel_interview_id = interviewRecordInserted.Relevel_Interview_Id__c;
                        response.status = interviewRecordInserted.Status__c;
                        response.LeadId = interviewRecordInserted.Lead__c;
                        response.message = 'Inserted';
                        response.status_code = '200';
                        System.debug('Successfully inserted Invoice. Invoice ID: ' + successRespo.getId());
                    }
                    else{
                        for ( Database.Error objErr : successRespo.getErrors() ){
                            System.debug(objErr.getStatusCode() + ': ' + objErr.getMessage());
                            System.debug('error:' + objErr.getFields());
                            response.message = 'Error Code' + objErr.getStatusCode() + ' Error Msg ' + objErr.getMessage();
                            response.status_code = '400';
                        }
                    }
                }
            } catch ( Exception e ){
                system.debug(e.getMessage());
                System.debug('at Line number =====> ' + e.getLineNumber());
                response.status_code = '400';
                response.message = e.getMessage();
            }
        }
        return response;
    }
    
    global class responseWrapper{
        global String interviewer_id;            //message string
        global String interviewer_name;        // Success String
        global String interviewer_email;
        global string meeting_url;
        global string relevel_interview_id;
        global String status;
        global String LeadId;
        global String message;
        global String status_code;
        
    }
    
}