force-app/main/default/objects/AO_Availability__c/AO_Availability__c.object-meta.xml
<CustomObject>
    <label>AO Availability</label>
    <nameField>
        <displayFormat>AOA - {000}</displayFormat>
        <label>AO Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Availabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Availability__c/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>Audit_Officer__c</referenceTo>
    <relationshipLabel>AO Availabilities</relationshipLabel>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Audited_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audited_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audited Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Checkout_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Checkout_DateTime__c</fullName>
    <label>Checkout DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Meeting</fullName>
            </value>
            <value>
                <fullName>On Break</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/User_Tracking__c.field-meta.xml
<CustomField>
    <fullName>User_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Tracking</label>
    <referenceTo>User_Tracking__c</referenceTo>
    <relationshipLabel>AO Availabilities</relationshipLabel>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Counsellor__c/Audit_Counsellor__c.object-meta.xml
<CustomObject>
    <label>Audit Counsellor</label>
    <nameField>
        <displayFormat>AC - {000}</displayFormat>
        <label>Audit Officer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Counsellors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Counsellor__c/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>Audit_Officer__c</referenceTo>
    <relationshipLabel>Audit Counsellors</relationshipLabel>
    <relationshipName>Audit_Counsellors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Counsellor__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Counsellors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Audit_Officer__c/Audit_Officer__c.object-meta.xml
<CustomObject>
    <label>Admission Officer</label>
    <nameField>
        <displayFormat>AO-{000}</displayFormat>
        <label>Audit Officer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admission Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Officer__c/fields/AO__c.field-meta.xml
<CustomField>
    <fullName>AO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AO</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Officers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/User_Tracking__c.object-meta.xml
<CustomObject>
    <label>User Tracking</label>
    <nameField>
        <displayFormat>UT-{0000}</displayFormat>
        <label>User Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Tracking__c/fields/Checkout_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Checkout_Datetime__c</fullName>
    <label>Checkout Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserTriggerHelper.cls
public class UserTriggerHelper {
    public Static Void checkingManagerandTranferLead(Map<Id, User> oldMap, Map<Id, User> newMap){
        try{
            set<Id> deactivatedUsersId = new Set<Id>();
            
            for(User userRec : newMap.values()){
                if(userRec.isActive != oldMap.get(userRec.id).isActive && userRec.isActive == false ){
                    if(userRec.ManagerId == null){
                        system.debug('Error');
                        userRec.Id.addError('Please Tag Manager to TRANSFER LEADS');
                    }else{
                        system.debug('No Error');
                        deactivatedUsersId.add(userRec.ID);
                    }
                }
            }
            system.debug('deactivatedUsersId>>'+deactivatedUsersId);
            if(!deactivatedUsersId.isEmpty()){
                UpdateLeadOwner.changeLeadOwnerShip(deactivatedUsersId);
                UpdateLeadOwner.removeCTILicence(deactivatedUsersId);
                DeleteAssignmentGroupMember.deleteAGM(deactivatedUsersId);
                updateAuditOfficerRecords(deactivatedUsersId);
                updateAuditCounsellorRecords(deactivatedUsersId);
            }
        }catch(Exception ex){
            system.debug('Erro>>'+ex.getMessage());
            system.debug('Error@@@'+ex.getLineNumber());
        }
    }
    
    public static void enbaleAOOnLogin(Id userId){
        
        
        if(userId != null){
            List<User_Tracking__c> userCheckout = New List<User_Tracking__c>();
            userCheckout =  [select id,Checkout_Datetime__c,Member__c from User_Tracking__c where Checkout_Datetime__c = null and Member__c =:userId and Createddate = today];
            if(userCheckout.size() > 0){
                List<AO_Availability__c> aoAvailabilityList = new List<AO_Availability__c>();
                aoAvailabilityList = [select id,status__c from AO_Availability__c where createddate = today and status__c = 'Not Available' and Audited_Officer__c =: userId];
                if(!aoAvailabilityList.isEmpty()){
                    for(AO_Availability__c ao : aoAvailabilityList){
                        ao.status__c = 'Available';
                    }
                    
                    update aoAvailabilityList;
                }
            }
            
        }
    }
    @future
    public static void updateAuditOfficerRecords(set<Id> deactivatedUsersId){
        delete[Select id,(Select Id from Audit_Counsellors__r) from Audit_Officer__c where AO__c in: deactivatedUsersId];
    }
    @future
    public static void updateAuditCounsellorRecords(set<Id> deactivatedUsersId){
       delete[select Id from Audit_Counsellor__c where User__c in:deactivatedUsersId ];
    }
}