force-app/main/default/objects/AO_Availability__c/AO_Availability__c.object-meta.xml
<CustomObject>
    <label>AO Availability</label>
    <nameField>
        <displayFormat>AOA - {000}</displayFormat>
        <label>AO Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Availabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Availability__c/fields/Audited_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audited_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audited Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Ideal_TIme__c.field-meta.xml
<CustomField>
    <fullName>Ideal_TIme__c</fullName>
    <formula>(NOW() -  Last_Engagement_Time__c )*24*60*60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ideal TIme</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Url__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url__c</fullName>
    <label>Meeting Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Meeting</fullName>
            </value>
            <value>
                <fullName>On Break</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interviewer_Email__c.field-meta.xml
<CustomField>
    <fullName>Interviewer_Email__c</fullName>
    <formula>Interviewer__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interviewer Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Interviewer_Name__c.field-meta.xml
<CustomField>
    <fullName>Interviewer_Name__c</fullName>
    <formula>Interviewer__r.FirstName+&quot; &quot;+Interviewer__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interviewer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Interviewer Not Found</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Interviewer Missed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
                <isActive>false</isActive>
                <label>Disqualified</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <isActive>false</isActive>
                <label>Qualified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AOAvalibilityModule.cls
public without sharing class AOAvalibilityModule {
    public AOAvalibilityModule() {

    }

    public static AO_Availability__c fetchAvailableAO(){
        try{
            List<AO_Availability__c> AOListTobeSend = new List<AO_Availability__c >();
            AO_Availability__c avilableAO = new AO_Availability__c();
            AOListTobeSend = [select id,Audited_Officer__c,Ideal_TIme__c,Meeting_Url__c,
                             Status__c,Meeting_Unique_Id__c	 from AO_Availability__c 
                             where createddate = today and status__c =: Constant.AVAILABLE_STATUS_TAG order by ideal_Time__c desc limit 1 ];
            avilableAO = [select id,Audited_Officer__c,Ideal_TIme__c,Meeting_Url__c,
                             Status__c,Meeting_Unique_Id__c	 from AO_Availability__c 
                             where createddate = today and status__c =: Constant.AVAILABLE_STATUS_TAG and Id =:AOListTobeSend[0].Id FOR UPDATE];
            if(!AOListTobeSend.isEmpty()){
                /*AOListTobeSend[0].status__c = 'In Meeting';
                update  AOListTobeSend;*/


                return avilableAO;
            }
            return null;
        }catch(Exception e){
            system.debug('Exception::'+e.getMessage());
            return null;
        }
    }

    @AuraEnabled(cacheable=true)
    public static Interview__c currentInterviewStatus(String LeadId){
        List<Interview__c> InterviewRec= new List<Interview__c>();
        try {
            System.debug('LeadId =====> ' + LeadId);
            InterviewRec = [SELECT Active__c,Id,Interviewer_Email__c,Interviewer_Name__c,Interviewer__c,Lead__c,Meeting_URL__c,Name,Status__c 
                                                FROM Interview__c
                                                Where Lead__c =: LeadId and Active__c = true];
            System.debug('InterviewRec =====> ' + InterviewRec[0]);
            
        } catch (Exception e) {
            //throw new AuraHandledException(e.getMessage());
            System.debug('trace ======> ' + e.getStackTraceString());
        }
        return InterviewRec[0];
    }

    @AuraEnabled
    public static String UpdateInterviewStatus(String Buttonlabel, Interview__c interRec){
        string msg = '';
        try {
            System.debug('Buttonlabel ====> ' + Buttonlabel);
            System.debug('interRec ======> ' + interRec);
            if (Buttonlabel=='End Meeting' && interRec.Status__c != 'Completed') {
                interRec.Status__c = 'Completed';
                update interRec;
                msg = 'SUCCESS';
            }
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return msg;
    }
}