force-app/main/default/objects/AO_Availability__c/AO_Availability__c.object-meta.xml
<CustomObject>
    <label>AO Availability</label>
    <nameField>
        <displayFormat>AOA - {000}</displayFormat>
        <label>AO Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Availabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Availability__c/fields/Audited_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audited_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audited Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Meeting</fullName>
            </value>
            <value>
                <fullName>On Break</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogoutEvent__c/LogoutEvent__c.object-meta.xml
<CustomObject>
    <label>LogoutEvent</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>LogoutEvent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LogoutEvents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogoutEvent__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LogoutEvents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LogoutEventHandler.cls
public class LogoutEventHandler {
	
    public static void disbaleAOOnLogout(list<LogoutEvent__c> logEvents){
        Set<Id> userIdTobeMarkUnavailable = new Set<Id>();
        for(LogoutEvent__c logEvent : logEvents){
            userIdTobeMarkUnavailable.add(logEvent.UserId__c);
        }
        
        if(!userIdTobeMarkUnavailable.isEmpty()){
            List<AO_Availability__c> aoAvailabilityList = new List<AO_Availability__c>();
            aoAvailabilityList = [select id,status__c from AO_Availability__c where createddate = today and status__c = 'Available' and Audited_Officer__c in: userIdTobeMarkUnavailable];
            
            if(!aoAvailabilityList.isEmpty()){
                for(AO_Availability__c ao : aoAvailabilityList){
                    ao.status__c = 'Not Available';
                }
                
                update aoAvailabilityList;
            }
        }
    }
}