force-app/main/default/objects/AO_Availability__c/AO_Availability__c.object-meta.xml
<CustomObject>
    <label>AO Availability</label>
    <nameField>
        <displayFormat>AOA - {000}</displayFormat>
        <label>AO Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Availabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Availability__c/fields/Audited_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audited_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audited Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <formula>DATETIMEVALUE(CreatedDate )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/User_Tracking__c.field-meta.xml
<CustomField>
    <fullName>User_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Tracking</label>
    <referenceTo>User_Tracking__c</referenceTo>
    <relationshipLabel>AO Availabilities</relationshipLabel>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/User_Tracking__c.object-meta.xml
<CustomObject>
    <label>User Tracking</label>
    <nameField>
        <displayFormat>UT-{0000}</displayFormat>
        <label>User Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Tracking__c/fields/Check_in_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_in_Date__c</fullName>
    <formula>DATEVALUE( Checkin_Detatime__c+ 30/1440)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Check in Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <formula>TEXT(Month( DATEVALUE(CreatedDate ) ))&amp;&quot;/&quot;&amp; TEXT(Day( DATEVALUE(CreatedDate ) )) &amp; &quot;/&quot; &amp; TEXT(Year( DATEVALUE(CreatedDate ) )) &amp; &quot; &quot; &amp; MID(TEXT(CreatedDate +330/1440 ),12,8)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserTrackingTriggerHelper.cls
public class UserTrackingTriggerHelper {
    public static void LinkAOWithUserTracking(Map<Id,User_Tracking__c> oldMap, Map<Id,User_Tracking__c> newMap){
        try{
            set<Id> AOIDs = new Set<Id>();
            List<AO_Availability__c> AOAvailabilityList =  new List<AO_Availability__c>();
            List<AO_Availability__c> AOAvailabilityListToUpdate =  new List<AO_Availability__c>();
            Map<String,User_Tracking__c> userTrackingRecByUserId = new Map<String,User_Tracking__c>();
            
            for(User_Tracking__c userTrackingRec : newMap.values()){
                if(userTrackingRec.Member__c != null && userTrackingRec.Check_in_Date__c != null){
                    AOIDs.add(userTrackingRec.Member__c);
                    userTrackingRecByUserId.put(userTrackingRec.Member__c, userTrackingRec);
                }
            }
            if(!AOIDs.isEmpty()){
                AOAvailabilityList = [Select Id,User_Tracking__c,Audited_Officer__c From AO_Availability__c where Audited_Officer__c In : userTrackingRecByUserId.keySet() AND Created_Date__c = today];
                if(!AOAvailabilityList.isEmpty()){
                    for(AO_Availability__c AOAvailRec : AOAvailabilityList){
                        AO_Availability__c AOAvailRecToUpdate = new AO_Availability__c();
                        AOAvailRecToUpdate.Id = AOAvailRec.Id;
                        AOAvailRecToUpdate.User_Tracking__c = userTrackingRecByUserId.containsKey(AOAvailRec.Audited_Officer__c)?userTrackingRecByUserId.get(AOAvailRec.Audited_Officer__c).Id:null;
                        
                        AOAvailabilityListToUpdate.add(AOAvailRecToUpdate);
                    }
                    if(!AOAvailabilityListToUpdate.isEmpty()){
                        update AOAvailabilityListToUpdate;
                    }
                }
            }
        }catch(exception ex){
            system.debug('Error==>' + ex.getMessage());
            system.debug('Error==>@@' + ex.getLineNumber());
        }
    }
}