force-app/main/default/objects/User_Tracking__c/User_Tracking__c.object-meta.xml
<CustomObject>
    <label>User Tracking</label>
    <nameField>
        <displayFormat>UT-{0000}</displayFormat>
        <label>User Tracking</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Tracking__c/fields/Check_in_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_in_Date__c</fullName>
    <formula>DATEVALUE( Checkin_Detatime__c+ 30/1440)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Check in Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Checkin_Detatime__c.field-meta.xml
<CustomField>
    <fullName>Checkin_Detatime__c</fullName>
    <label>Checkin Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/fields/Checkout_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Checkout_Datetime__c</fullName>
    <label>Checkout Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BatchToAutoCheckOutAtNine.cls
public class BatchToAutoCheckOutAtNine implements Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext BC) {
        Date todayDate = System.today();
        
        String query = 'SELECT id,Checkout_Datetime__c,Check_in_Date__c FROM User_Tracking__c WHERE Checkout_Datetime__c = null AND Checkin_Detatime__c != null';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<User_Tracking__c> userTrackingList){
        try{
            time everyDayNine = time.newInstance(21, 00, 00, 00);
            if(!userTrackingList.isEmpty()){
                for(User_Tracking__c userTrackingRec : userTrackingList){
                    userTrackingRec.Checkout_Datetime__c = DateTime.newInstance(userTrackingRec.Check_in_Date__c, everyDayNine);
                }
                update userTrackingList;
            }
        }
        catch(exception e){
            System.debug('An exception occurred: ' + e.getMessage() + 'at line number :: ' + e.getLineNumber());
            
        }
    }
    public void finish(Database.BatchableContext BC) {
    }  
}