force-app/main/default/objects/Whiteboard_Markings__c/Whiteboard_Markings__c.object-meta.xml
<CustomObject>
    <label>Whiteboard Marking</label>
    <nameField>
        <displayFormat>Markings-{000000}</displayFormat>
        <label>Whiteboard Markings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Whiteboard Markings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Whiteboard_Markings__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <label>Notification</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Whiteboard_Markings__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BDE</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Senior Sales Manager</fullName>
            </value>
            <value>
                <fullName>ADMIN</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Whiteboard_Markings__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start  Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/WhiteboardOutputHelper.cls
public class WhiteboardOutputHelper {
    @AuraEnabled
    public static List<Whiteboard_Markings__c> getWhiteBoardMarkings(){
        id currentUserId = userinfo.getProfileId();
        String profileName ;
        List<Whiteboard_Markings__c> whiteboardUpdates = new List<Whiteboard_Markings__c>();
        
        if(!string.isBlank(currentUserId)){
            profileName = [select Name from profile where id = : currentUserId].Name;
            if(!String.isBlank(profileName)){
                whiteboardUpdates = [Select Id,End_Date__c,Notification__c,Profile__c,Start_Date__c From Whiteboard_Markings__c Where Profile__c =: profileName OR Profile__c = 'All' limit 2];
            }
        }
        system.debug('whiteboardUpdates-->'+whiteboardUpdates);
        return whiteboardUpdates;
    }
}