force-app/main/default/objects/AO_Activity__c/AO_Activity__c.object-meta.xml
<CustomObject>
    <label>AO Activity</label>
    <nameField>
        <displayFormat>AOAct-{0000000}</displayFormat>
        <label>AO Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Activity__c/fields/AO_Availability__c.field-meta.xml
<CustomField>
    <fullName>AO_Availability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AO Availability</label>
    <referenceTo>AO_Availability__c</referenceTo>
    <relationshipLabel>AO Activities</relationshipLabel>
    <relationshipName>AO_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/AO_Member__c.field-meta.xml
<CustomField>
    <fullName>AO_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AO Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AO_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>End_DateTime__c</fullName>
    <label>End DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Interview__c.field-meta.xml
<CustomField>
    <fullName>Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipLabel>AO Activities</relationshipLabel>
    <relationshipName>AO_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>AO Activities</relationshipLabel>
    <relationshipName>AO_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Meeting_Url__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url__c</fullName>
    <label>Meeting Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/AO_Availability__c.object-meta.xml
<CustomObject>
    <label>AO Availability</label>
    <nameField>
        <displayFormat>AOA - {000}</displayFormat>
        <label>AO Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Availabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Availability__c/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>Audit_Officer__c</referenceTo>
    <relationshipLabel>AO Availabilities</relationshipLabel>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Audited_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audited_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audited Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Checkin_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Checkin_DateTime__c</fullName>
    <label>Checkin DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Url__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url__c</fullName>
    <label>Meeting Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Meeting</fullName>
            </value>
            <value>
                <fullName>On Break</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Officer__c/Audit_Officer__c.object-meta.xml
<CustomObject>
    <label>Admission Officer</label>
    <nameField>
        <displayFormat>AO-{000}</displayFormat>
        <label>Audit Officer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admission Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Interviewer Not Found</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Interviewer Missed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
                <isActive>false</isActive>
                <label>Disqualified</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <isActive>false</isActive>
                <label>Qualified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InterviewTriggerHandler.cls
public without sharing class InterviewTriggerHandler{
    public static void DeactivateInterview(List<Interview__c> listofInterviews, Map<Id, Interview__c> oldMapInterview){
        Set<Id> leadIdSet = New Set<Id>();
        for ( Interview__c intRec : listofInterviews ){
            //ACCEPTED_OFFER = Accepted
            //REJECTED_OFFER = 'Rejected'
            //COMPLETED_OFFER = 'Completed'
            //INTERVIEW_STATUS_MISSED = 'Missed'
            //INTERVIEW_STATUS_INTERVIEW_MISSED = 'Interviewer Missed'
            if ( intRec.Status__c != oldMapInterview.get(intRec.Id).Status__c && ( intRec.Status__c == Constant.ACCEPTED_OFFER || intRec.Status__c == Constant.REJECTED_OFFER || intRec.Status__c == Constant.COMPLETED_OFFER 
                                                                                 || intRec.Status__c == Constant.INTERVIEW_STATUS_MISSED || intRec.Status__c == Constant.INTERVIEW_STATUS_INTERVIEW_MISSED) ){
                intRec.Active__c = false;
                intRec.End_Time__c = system.now();                                                                     
                leadIdSet.add(intRec.Lead__c);
                                                                                     
            }
        }
        
        if(!leadIdSet.isEmpty()){
            List<Task> taskListTobeUpdate = [select id,WhoId,Status from task where WhoId in: leadIdSet and Subject =: system.label.Interview_Task_Subject and Status = 'Open'];
            if(!taskListTobeUpdate.isEmpty()){
                for(Task ts : taskListTobeUpdate){
                    ts.status = 'Completed';
                }
                
                update taskListTobeUpdate;
            }
            
        }
    }

    public static void CreateAndAssignTaskWithAOAssignment(Map<Id, Interview__c> oldMapInterview, Map<Id, Interview__c> newMapInterview){
        List<task> taskListToBeAssignedToAO = new List<Task>();
        set<String> recipientsIds = new set<String>();
        set<id> LeadIds = new Set<Id>(); //leadByIdMap
        List<Lead> LeadList = new List<Lead>();
        map<Id, Lead> leadByIdMap = new map<Id, Lead>();
        List<AO_Availability__c> AOAvailableListTobeUpdated = new List<AO_Availability__c>();
        List<AO_Availability__c> UpdatedAOAvailableList = new List<AO_Availability__c>();
        try{
            if ( !newMapInterview.isEmpty() ){
                for ( Interview__c Interview : newMapInterview.values() ){
                    if ((Interview.Interviewer__c != null && oldMapInterview == null) || (Interview.Interviewer__c != null && oldMapInterview != null && Interview.Interviewer__c != oldMapInterview.get(Interview.id).Interviewer__c)){                         //Interview.Interviewer__c != oldMapInterview.get(Interview.Id).Interviewer__c 
                        recipientsIds.add(Interview.Interviewer__c);
                        LeadIds.add(Interview.Lead__c);
                        task tsk = new Task();
                        tsk.Subject = system.label.Interview_Task_Subject;
                        tsk.Status = 'Open';
                        tsk.Priority = 'High';
                        tsk.WhoId = Interview.Lead__c;
                        tsk.OwnerId = Interview.Interviewer__c;
                        tsk.Meeting_URL__c = Interview.Meeting_URL__c;
                        tsk.IsReminderSet = true;
                        tsk.ReminderDateTime = System.now();
                        taskListToBeAssignedToAO.add(tsk);
                        if ( !LeadIds.isEmpty() ){
                            LeadList = [Select Id, FirstName, LastName, Name
                                        From Lead
                                        Where Id In:LeadIds];
                        }
                        if ( !LeadList.isEmpty() ){
                            for ( Lead ld : LeadList ){
                                leadByIdMap.put(ld.Id, ld);
                            }
                        }
                        if (!recipientsIds.isEmpty()) {
                            AOAvailableListTobeUpdated = [Select Id, Audited_Officer__c,Checkin_DateTime__c, Meeting_Url__c, Status__c
                                                        From AO_Availability__c
                                                        Where Audited_Officer__c IN : recipientsIds And CreatedDate = TODAY];
                            
                            if (!AOAvailableListTobeUpdated.isEmpty()) {
                                for (AO_Availability__c AOAvailable : AOAvailableListTobeUpdated) {
                                    AOAvailable.status__c = 'In Meeting';
                                    UpdatedAOAvailableList.add(AOAvailable);
                                }
                            }
                        }
                    }
                }
            }
            if (!UpdatedAOAvailableList.isEmpty()) {
                update UpdatedAOAvailableList;
            }
            if ( !taskListToBeAssignedToAO.isEmpty()){
                insert taskListToBeAssignedToAO;
            }
            if (!leadByIdMap.isEmpty() && !recipientsIds.isEmpty()) {
                CustomNotifications.notifyUsers(recipientsIds, leadByIdMap);
            }
        }
        catch ( Exception e ){
            System.debug('This error has occured due to =======> ' + e.getMessage() + ' at Line Number  ========> ' + e.getLineNumber());

        }
    }
    
    public static void createAOActivitiesLog(List<Interview__c> interviewList,Map<Id,Interview__c> mapofOldInterviewRec){
        List<AO_Activity__c> aoActivitiesToBeInsert = new List<AO_Activity__c>();
        List<AO_Availability__c> listodAOAvalability = new List<AO_Availability__c>();
        Map<Id,Id> mapofAOIdByAOId = new Map<Id,Id>();
        listodAOAvalability = [select id,Audit_Officer__c,Audited_Officer__c from AO_Availability__c where createddate = today];
        for(AO_Availability__c ao : listodAOAvalability){
            mapofAOIdByAOId.put(ao.Audited_Officer__c,ao.Id);
        }
        for(Interview__c InterRecord : interviewList){
            if(InterRecord.Status__c != null && InterRecord.Status__c != mapofOldInterviewRec.get(InterRecord.Id).Status__c && (InterRecord.Status__c == Constant.INTERVIEW_STATUS_INTERVIEW_MISSED || InterRecord.Status__c == 'Accepted' || InterRecord.Status__c == 'Rejected' || InterRecord.Status__c == 'Missed' || InterRecord.Status__c == 'Completed')){
                AO_Activity__c aoActivity = new AO_Activity__c();
                aoActivity.AO_Availability__c = mapofAOIdByAOId.get(InterRecord.Interviewer__c);
                aoActivity.AO_Member__c = InterRecord.Interviewer__c;
                aoActivity.Meeting_Unique_Id__c = InterRecord.Meeting_Unique_Id__c;
                aoActivity.Meeting_Url__c = InterRecord.Meeting_Url__c;
                aoActivity.StartTime__c = InterRecord.CreatedDate;
                aoActivity.End_DateTime__c = InterRecord.End_Time__c;
                aoActivity.Interview__c = InterRecord.Id;
                aoActivity.Lead__c = InterRecord.Lead__c;
                aoActivitiesToBeInsert.add(aoActivity);
            }
        }
        
        if(!aoActivitiesToBeInsert.isEmpty()){
            insert aoActivitiesToBeInsert;
        }
    }

    public static void CreateNextMeetingLinkForSM(Map<Id, Interview__c> newMapInterview , Map<Id, Interview__c> oldMapInterview) {

        System.debug('newMapInterview =====> ' + newMapInterview);
        System.debug('oldMapInterview =====> ' + oldMapInterview);
        Set<String> InterviewIds = new Set<String>();
        Map<Id,Interview__c> mapofInterviewerIdByInterviewId = new Map<Id,Interview__c>();
        if (!newMapInterview.isEmpty()) {
            for (Interview__c InterRecord : newMapInterview.values()) {
                if (InterRecord.Status__c != null && InterRecord.Status__c != oldMapInterview.get(InterRecord.Id).Status__c && (InterRecord.Status__c == 'Accepted' || InterRecord.Status__c == 'Rejected' || InterRecord.Status__c == 'Missed' || InterRecord.Status__c == 'Interviewer Missed' || InterRecord.Status__c == 'Completed')){
                    InterviewIds.add(InterRecord.Interviewer__c);
                    mapofInterviewerIdByInterviewId.put(InterRecord.Interviewer__c,InterRecord);
                }
            }
            System.debug('InterviewIds ======> ' + InterviewIds);
            System.debug('InterviewIds =====>' + InterviewIds.size());
            if (!InterviewIds.isEmpty()) {
                for (String InterviewId : InterviewIds) {
                    CallingSMLinkGeneratorInFuture.SMLinkGenratorInFuture(InterviewId);
                }
            }
        }
    }

    public static void updateIntervieStatusToBackend(Map<Id, Interview__c> newMapInterview , Map<Id, Interview__c> oldMapInterview) {

        System.debug('newMapInterview =====> ' + newMapInterview);
        System.debug('oldMapInterview =====> ' + oldMapInterview);
        Set<String> InterviewIds = new Set<String>();

        if (!newMapInterview.isEmpty()) {
            system.debug('Inside newmapinterview');
            for (Interview__c InterRecord : newMapInterview.values()) {
                system.debug('inside for loop');
                if (InterRecord.Status__c != null && InterRecord.Status__c != oldMapInterview.get(InterRecord.Id).Status__c && (InterRecord.Status__c == Constant.INTERVIEW_STATUS_INTERVIEW_MISSED || InterRecord.Status__c == 'Accepted' || InterRecord.Status__c == 'Rejected' || InterRecord.Status__c == 'Missed' || InterRecord.Status__c == 'Completed')){ //|| InterRecord.Status__c == 'Qualified' || InterRecord.Status__c == 'Disqualified'
                    InterviewIds.add(InterRecord.Id);
                }
                system.debug('InterviewIds::'+InterviewIds);
            }
            Callout_Interview_Response.sendInterviewStatusUpdate(InterviewIds);
        }
        
    }
    
    public static void assignCounsellorLogic(List<Interview__c> interviewList,Map<Id, Interview__c> oldMapInterview){
        Set<Id> leadIdSet = New Set<Id>();
        for(Interview__c intRec : interviewList){
            if((intRec.Status__c == 'Accepted' || intRec.Status__c == 'Rejected') && intRec.Status__c != oldMapInterview.get(intRec.Id).Status__c){
                leadIdSet.add(intRec.Lead__c);
            }
        }
        
        if(!leadIdSet.isEmpty()){
            List<Lead> leadList = [select id,ownerId from Lead where id in: leadIdSet ];
            if(!leadList.isEmpty()){
                CounsellorsAssignmentModule.counsellorAssignmentLogic(leadList);
            }
        }
    }

}