force-app/main/default/objects/AO_Activity__c/AO_Activity__c.object-meta.xml
<CustomObject>
    <label>AO Activity</label>
    <nameField>
        <displayFormat>AOAct-{0000000}</displayFormat>
        <label>AO Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Activity__c/fields/AO_Availability__c.field-meta.xml
<CustomField>
    <fullName>AO_Availability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AO Availability</label>
    <referenceTo>AO_Availability__c</referenceTo>
    <relationshipLabel>AO Activities</relationshipLabel>
    <relationshipName>AO_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Interview__c.field-meta.xml
<CustomField>
    <fullName>Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipLabel>AO Activities</relationshipLabel>
    <relationshipName>AO_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>AO Activities</relationshipLabel>
    <relationshipName>AO_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Meeting_Url__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url__c</fullName>
    <label>Meeting Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/AO_Availability__c.object-meta.xml
<CustomObject>
    <label>AO Availability</label>
    <nameField>
        <displayFormat>AOA - {000}</displayFormat>
        <label>AO Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Availabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Availability__c/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>Audit_Officer__c</referenceTo>
    <relationshipLabel>AO Availabilities</relationshipLabel>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Url__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url__c</fullName>
    <label>Meeting Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Meeting</fullName>
            </value>
            <value>
                <fullName>On Break</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Counsellor__c/Audit_Counsellor__c.object-meta.xml
<CustomObject>
    <label>Audit Counsellor</label>
    <nameField>
        <displayFormat>AC - {000}</displayFormat>
        <label>Audit Officer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Counsellors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Counsellor__c/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>Audit_Officer__c</referenceTo>
    <relationshipLabel>Audit Counsellors</relationshipLabel>
    <relationshipName>Audit_Counsellors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Interviewer Not Found</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Interviewer Missed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
                <isActive>false</isActive>
                <label>Disqualified</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <isActive>false</isActive>
                <label>Qualified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Goal_Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Goal_Interested_In__c</fullName>
    <label>Course Interested In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
            </value>
            <value>
                <fullName>HR-Generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
                <label>Operations-Associate</label>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
            <value>
                <fullName>Conducted</fullName>
            </value>
            <value>
                <fullName>Offer Rolled Out</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Called</fullName>
            </value>
            <value>
                <fullName>Nurturing</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Learner_Uid__c.field-meta.xml
<CustomField>
    <fullName>Learner_Uid__c</fullName>
    <defaultValue>&quot;CTI&quot;</defaultValue>
    <label>Learner Uid</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Payment_details__c.field-meta.xml
<CustomField>
    <fullName>Payment_details__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Payment details</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source_Intent__c.field-meta.xml
<CustomField>
    <fullName>Source_Intent__c</fullName>
    <label>Source Intent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
                <label>data-analytics</label>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
                <label>associate-product-management</label>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
                <label>business-analytics</label>
            </value>
            <value>
                <fullName>android-development</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
            </value>
            <value>
                <fullName>hr-generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
            <value>
                <fullName>Front-End</fullName>
                <isActive>false</isActive>
                <label>Front-End</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
                <default>true</default>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_TriggerCoverage.cls
@isTest
public class Test_TriggerCoverage {
    
    @isTest
    public static void triggerTest(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser90@testorg.com');
        insert u;
        Lead leads = new Lead();
        leads.Lead_Assigned_Date__c = Date.today();
        leads.FirstName='test';
        leads.LastName='Last Name';
        leads.Source_Intent__c='Backend-Development';
        leads.Goal_Interested_In__c='FrontEnd-Development';
        leads.Company='test';
        leads.Learner_Uid__c='test';
        leads.Payment_details__c=2.0;
        leads.Learner_Uid__c='test UID';
        leads.Temperature__c = 'Hot';
        //leads.Lead_Stage__c='New';
        leads.OwnerId = u.id;
        insert leads;
        
        Interview__c intRec = new Interview__c();
        intRec.Lead__c = leads.Id;
        intRec.Interviewer__c = leads.OwnerId;
        intRec.Meeting_URL__c = 'test';
        intRec.Status__c = 'Started';
        insert intRec;
        
        /*intrec.Status__c = 'Completed';
update intrec;*/
        
        AO_Availability__c ao = new AO_Availability__c();
        ao.Status__c = 'Available';
        //ao.Audit_Officer__c = u.id;
        insert ao;
        
        ao.Status__c = 'In Meeting';
        update ao;
        
        AO_Activity__c AO_Act = new AO_Activity__c();
        AO_Act.Meeting_Url__c = 'https://relevel--uat.sandbox.lightning.force.com/lightning/page/home';
        AO_Act.Meeting_Unique_Id__c = 'AUVSUWFBJ83V83BC83B46VD6302';
        AO_Act.Lead__c = leads.id;
        Insert AO_Act;
        AO_Act.Description__c = 'hii how are you?';
        AO_Act.Event_Status__c = 'Completed';
        update AO_Act;
        
    }
    @isTest
    public static void logoutEventTest(){
        Test.startTest();    
        EventBus.publish(new LogoutEventStream());
        Test.stopTest();
    }
    @isTest
    public static void auditCounsellorTest(){
        Test.startTest();    
        Audit_Counsellor__c auditCounsellorRec = new Audit_Counsellor__c ();
        insert auditCounsellorRec;
        delete [Select Id from Audit_Counsellor__c];
        Test.stopTest();
    }
    @isTest
    public static void usertrackingTriggerTest(){
        Test.startTest();    
        User_Tracking__C userTrackingRec = new User_Tracking__C ();
        insert userTrackingRec;
        Test.stopTest();
    }
}