force-app/main/default/objects/AO_Activity__c/AO_Activity__c.object-meta.xml
<CustomObject>
    <label>AO Activity</label>
    <nameField>
        <displayFormat>AOAct-{0000000}</displayFormat>
        <label>AO Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Activity__c/fields/AO_Availability__c.field-meta.xml
<CustomField>
    <fullName>AO_Availability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AO Availability</label>
    <referenceTo>AO_Availability__c</referenceTo>
    <relationshipLabel>AO Activities</relationshipLabel>
    <relationshipName>AO_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>End_DateTime__c</fullName>
    <label>End DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Event_Actual_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Actual_End_Time__c</fullName>
    <label>Actual End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Event_Actual_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Actual_Start_Time__c</fullName>
    <label>Actual Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Gmeet_call_Duration__c.field-meta.xml
<CustomField>
    <fullName>Gmeet_call_Duration__c</fullName>
    <label>Gmeet call Duration(in min)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Is_Gmeet_Recording_Available__c.field-meta.xml
<CustomField>
    <fullName>Is_Gmeet_Recording_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Gmeet Recording Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Meeting_Url__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url__c</fullName>
    <label>Meeting Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Meeting_Url_Charcter__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url_Charcter__c</fullName>
    <formula>RIGHT(Meeting_Url__c , 12 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Meeting Url Charcter</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Recording_URL__c.field-meta.xml
<CustomField>
    <fullName>Recording_URL__c</fullName>
    <label>Recording URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/AO_Availability__c.object-meta.xml
<CustomObject>
    <label>AO Availability</label>
    <nameField>
        <displayFormat>AOA - {000}</displayFormat>
        <label>AO Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Availabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Availability__c/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>Audit_Officer__c</referenceTo>
    <relationshipLabel>AO Availabilities</relationshipLabel>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Url__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url__c</fullName>
    <label>Meeting Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Audit_Officer__c/Audit_Officer__c.object-meta.xml
<CustomObject>
    <label>Admission Officer</label>
    <nameField>
        <displayFormat>AO-{000}</displayFormat>
        <label>Audit Officer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admission Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Officer__c/fields/AO__c.field-meta.xml
<CustomField>
    <fullName>AO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AO</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Officers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchToUpdateAllAOActivities.cls
public with sharing class BatchToUpdateAllAOActivities implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful{
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        
        //datetime dt = system.today();
        datetime ct = system.now();
        datetime QueryStartTime = Datetime.newInstance(ct.year(), ct.month(), ct.day(), 5, 31, 0);        
       	datetime QueryEndTime = Datetime.newInstance(ct.year(), ct.month(), ct.day(), ct.hour()+5, ct.minute()+10, 0);
        //String newQueryString = 'SELECT AO_Availability__c,Attendees__c,Description__c,End_DateTime__c,Event_Actual_End_Time__c,Event_Actual_Start_Time__c,Event_Status__c,Gmeet_call_Duration__c,Id,Is_Gmeet_Recording_Available__c,Meeting_Unique_Id__c,Meeting_Url__c,Recording_URL__c FROM AO_Activity__c where Event_Status__c != \'Completed\' AND StartTime__c >=: QueryStartTime And End_DateTime__c <=: QueryEndTime';
        String newQueryString = 'SELECT AO_Availability__c,Attendees__c,Description__c,End_DateTime__c,Event_Actual_End_Time__c,Event_Actual_Start_Time__c,Event_Status__c,Gmeet_call_Duration__c,Id,Is_Gmeet_Recording_Available__c,Meeting_Unique_Id__c,Meeting_Url__c,Recording_URL__c, Meeting_Url_Charcter__c,AO_Availability__r.Audit_Officer__r.AO__c FROM AO_Activity__c where Event_Status__c != \'Completed\' AND StartTime__c >=: QueryStartTime And End_DateTime__c <=: QueryEndTime';
        return Database.getQueryLocator(newQueryString);
        
    }

    public void execute(Database.BatchableContext bc, List<AO_Activity__c> AOActivitiesRecords){
        System.debug('AOActivitiesRecords =====> ' + AOActivitiesRecords);
        if(!AOActivitiesRecords.isEmpty()){
            for(AO_Activity__c AO_Act :AOActivitiesRecords){
                if(AO_Act.Description__c == null && AO_Act.Meeting_Unique_Id__c  != null && (AO_Act.Event_Status__c == null || AO_Act.Event_Status__c != 'Completed')){
                    SMMeetingLinkGenerator.UpdateAOActivitiesLog(AO_Act);
                }
            }
        }


    }
    public void finish(Database.BatchableContext bc){
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors,
                            JobItemsProcessed,
                            TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];

    }
    
}