force-app/main/default/objects/AO_Activity__c/AO_Activity__c.object-meta.xml
<CustomObject>
    <label>AO Activity</label>
    <nameField>
        <displayFormat>AOAct-{0000000}</displayFormat>
        <label>AO Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Activity__c/fields/AO_Availability__c.field-meta.xml
<CustomField>
    <fullName>AO_Availability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AO Availability</label>
    <referenceTo>AO_Availability__c</referenceTo>
    <relationshipLabel>AO Activities</relationshipLabel>
    <relationshipName>AO_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/AO_Member__c.field-meta.xml
<CustomField>
    <fullName>AO_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AO Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AO_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>End_DateTime__c</fullName>
    <label>End DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Event_Actual_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Actual_End_Time__c</fullName>
    <label>Actual End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Event_Actual_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Actual_Start_Time__c</fullName>
    <label>Actual Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Gmeet_call_Duration__c.field-meta.xml
<CustomField>
    <fullName>Gmeet_call_Duration__c</fullName>
    <label>Gmeet call Duration(in min)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Interview__c.field-meta.xml
<CustomField>
    <fullName>Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipLabel>AO Activities</relationshipLabel>
    <relationshipName>AO_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Is_Gmeet_Recording_Available__c.field-meta.xml
<CustomField>
    <fullName>Is_Gmeet_Recording_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Gmeet Recording Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>AO Activities</relationshipLabel>
    <relationshipName>AO_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Meeting_Url__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url__c</fullName>
    <label>Meeting Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Meeting_Url_Charcter__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url_Charcter__c</fullName>
    <formula>RIGHT(Meeting_Url__c , 12 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Meeting Url Charcter</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Activity__c/fields/Recording_URL__c.field-meta.xml
<CustomField>
    <fullName>Recording_URL__c</fullName>
    <label>Recording URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/AO_Availability__c.object-meta.xml
<CustomObject>
    <label>AO Availability</label>
    <nameField>
        <displayFormat>AOA - {000}</displayFormat>
        <label>AO Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Availabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Meeting_Url__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Url__c</fullName>
    <label>Meeting Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Meeting_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Unique_Id__c</fullName>
    <label>Meeting Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Actual_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Time__c</fullName>
    <label>Actual End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Actual_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Time__c</fullName>
    <label>Actual Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AOActivitiesTriggerHandler.cls
public class AOActivitiesTriggerHandler {
    
    public static void CreateEvent_AOActivities(Map<Id, AO_Activity__c> AoActNewMap, List<AO_Activity__c> AoActNewList){
        List<Event> EventListToBeInserted = new List<Event>();
        Set<Id> aoActId = new Set<Id>();
        for(AO_Activity__c aoAct : AoActNewList){
            aoActId.add(aoAct.Id);
        }
        
        List<AO_Activity__c> detailedActList = [select id,Lead__r.name,AO_Member__r.Name,Meeting_Unique_Id__c,AO_Availability__c,
                                                Meeting_Url__c,StartTime__c,End_DateTime__c,Interview__c,Lead__c from AO_Activity__c where id in: aoActId];
        
        
        try {
            if (!detailedActList.isEmpty()) {
                for (AO_Activity__c AOAct : detailedActList) {
                    Event createEvent = new Event();
                    createEvent.Subject = 'Google Meet with ' + AOAct.Lead__r.name +' By ' + AOAct.AO_Member__r.Name;
                    createEvent.GMeet_Event_Id__c = AOAct.Meeting_Unique_Id__c;
                    //createEvent.AO_Member__c = AOAct.AO_Member__c;
                    createEvent.AO_Availability__c = AOAct.AO_Availability__c;
                    createEvent.Meeting_URL__c = AOAct.Meeting_Url__c;
                    createEvent.StartDateTime = AOAct.StartTime__c;
                    createEvent.EndDateTime = AOAct.End_DateTime__c;
                    createEvent.Interview__c = AOAct.Interview__c;
                    createEvent.WhoId = AOAct.Lead__c;
                    EventListToBeInserted.add(createEvent);
                }
                if (!EventListToBeInserted.isEmpty()) {
                    insert EventListToBeInserted;
                }
            }
        } catch (Exception e) {
            System.debug('The error has occurred due to ==== > ' + e.getStackTraceString());            
        }
    }
    
    public static void UpdateEvent_AOactivities(Map<Id, AO_Activity__c> AoActNewMap, Map<Id, AO_Activity__c> AoActOldMap){
        
        try {
            Set<Id> LeadIds = new Set<Id>();
            List<Event> EventListToBeUpdated = new List<Event>();
            List<Event> UpdatedEventList = new List<Event>();
            List<Lead> leadListToUpdate = new List<Lead>();
            Map<Id, AO_Activity__c> MapofLeadIdWithAOact = new Map<Id, AO_Activity__c>();
            
            if (!AoActNewMap.isEmpty()) {
                for (AO_Activity__c AO_Update : AoActNewMap.values()) {
                    if (AO_Update.Event_Status__c != null && AO_Update.Event_Status__c == 'Completed' && AO_Update.Description__c != null) {
                        LeadIds.add(AO_Update.Lead__c);
                        MapofLeadIdWithAOact.put(AO_Update.Lead__c, AO_Update);
                    }
                }
                if (!MapofLeadIdWithAOact.isEmpty()) {
                    EventListToBeUpdated = [SELECT AccountId,Actual_Attendees_Email_List__c,AO_Availability__c,Attendees_Except_BDE__c,Attendees_list__c,Attendees__c,Description,EndDateTime,Event_Actual_End_Time__c,Event_Actual_Start_Time__c,Event_Description__c,Event_Status__c,Gmeet_call_Duration__c,GMeet_Event_Id__c,Interview__c,IsGmeetRecordingAvailable__c,meeting_Url_Charcter__c,Meeting_URL__c,WhoId 
                                            FROM Event
                                            Where whoId IN: LeadIds];
                    if (!EventListToBeUpdated.isEmpty()) {
                        for (Event EventTobeupdated : EventListToBeUpdated) {
                            if (MapofLeadIdWithAOact.containsKey(EventTobeupdated.whoId)) {
                                Event updatedEvent = new Event();
                                updatedEvent.id = EventTobeupdated.id;
                                updatedEvent.Recording_URL__c = MapofLeadIdWithAOact.get(EventTobeupdated.whoId).Recording_URL__c;
                                updatedEvent.Event_Actual_Start_Time__c = MapofLeadIdWithAOact.get(EventTobeupdated.whoId).Event_Actual_Start_Time__c;
                                updatedEvent.Event_Actual_End_Time__c = MapofLeadIdWithAOact.get(EventTobeupdated.whoId).Event_Actual_End_Time__c;
                                updatedEvent.Description = MapofLeadIdWithAOact.get(EventTobeupdated.whoId).Description__c;
                                updatedEvent.Event_Status__c = MapofLeadIdWithAOact.get(EventTobeupdated.whoId).Event_Status__c;
                                updatedEvent.Gmeet_call_Duration__c = MapofLeadIdWithAOact.get(EventTobeupdated.whoId).Gmeet_call_Duration__c;
                                updatedEvent.IsGmeetRecordingAvailable__c = MapofLeadIdWithAOact.get(EventTobeupdated.whoId).Is_Gmeet_Recording_Available__c;
                                Lead leadRec = new Lead();
                                leadRec.Id = EventTobeupdated.whoId;
                                leadRec.Actual_Start_Time__c = MapofLeadIdWithAOact.get(EventTobeupdated.whoId).Event_Actual_Start_Time__c;
                                leadRec.Actual_End_Time__c = MapofLeadIdWithAOact.get(EventTobeupdated.whoId).Event_Actual_End_Time__c;
                                leadListToUpdate.add(leadRec);
                                UpdatedEventList.add(updatedEvent);
                            }
                        }
                    }
                }
                if (!UpdatedEventList.isEmpty()) {
                    update UpdatedEventList;
                }
                if(!leadListToUpdate.isEmpty()){
                    update leadListToUpdate;
                }
            }
            
        } catch (Exception e) {
            
        }
        
    }
    
}