force-app/main/default/objects/APILog__c/APILog__c.object-meta.xml
<CustomObject>
    <label>APILog</label>
    <nameField>
        <displayFormat>API-{0000}</displayFormat>
        <label>APILogs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APILogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APILog__c/fields/Event_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Event_Record_ID__c</fullName>
    <label>Event Record ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APILog__c/fields/ResponseMap__c.field-meta.xml
<CustomField>
    <fullName>ResponseMap__c</fullName>
    <label>ResponseMap</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/APILog__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>APILogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/APILOGSCapture.cls
public with sharing class APILOGSCapture {

    public static void captureLogs(String EndPoint, String body, integer statuscode, String Response, String ResponseMap,string Eventid){

        try {
            APILog__c APIL = new APILog__c();
            if(Eventid != null && statuscode != null && Response != null){
                APIL.Body__c = body;
                APIL.Endpoint__c = EndPoint;
                APIL.Event_Record_ID__c = Eventid;
                APIL.Response__c = Response;
                APIL.StatusCode__c = statuscode;
                APIL.User__c = UserInfo.getUserId();

                if(ResponseMap != null){
                    APIL.ResponseMap__c = ResponseMap;
                }
                else{
                    APIL.ResponseMap__c= '';
                }
                System.debug(' APIL  =======> ' + APIL);
                insert APIL;
            }
            
        } catch (Exception e) {
            System.debug('The Error occured due to ======> ' + e.getMessage());
            System.debug('The Error occured at line number ======> ' + e.getLineNumber());
            
        }
    }
}