force-app/main/default/objects/Lead/fields/AO_Interview_Status_Manual__c.field-meta.xml
<CustomField>
    <fullName>AO_Interview_Status_Manual__c</fullName>
    <label>AO Interview Status (Manual)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Learner No-Show</fullName>
            </value>
            <value>
                <fullName>AO No-Show</fullName>
            </value>
            <value>
                <fullName>Conducted</fullName>
            </value>
            <value>
                <fullName>Joined &amp; Dropped</fullName>
                <isActive>false</isActive>
                <label>Joined &amp; Dropped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Interview_Id__c.field-meta.xml
<CustomField>
    <fullName>Interview_Id__c</fullName>
    <label>Interview Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_Interview_Conducted__c.field-meta.xml
<CustomField>
    <fullName>Is_Interview_Conducted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Interview Conducted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <formula>Owner:User.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
            <value>
                <fullName>Conducted</fullName>
            </value>
            <value>
                <fullName>Offer Rolled Out</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Called</fullName>
            </value>
            <value>
                <fullName>Nurturing</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Version__c.field-meta.xml
<CustomField>
    <fullName>Lead_Version__c</fullName>
    <label>Lead Version</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V0</fullName>
            </value>
            <value>
                <fullName>V1</fullName>
                <default>true</default>
                <label>V1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>Offer_Status__c</fullName>
    <formula>IF( ISPICKVAL(Profession__c,&apos;&apos;) || ISPICKVAL(Communication__c , &apos;&apos;) || ISPICKVAL(Intent__c, &apos;&apos; )|| ISPICKVAL(Financials__c ,&apos;&apos;), &apos;&apos;, &apos;Yes&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Send Admission Letter</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchToTransferLeadToQueue.cls
public with sharing class BatchToTransferLeadToQueue implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful{
    

    public Database.QueryLocator start(Database.BatchableContext bc) {
        
        string queueId = [SELECT Id, Type
                          FROM Group
                          WHERE Type = 'Queue' AND Name = 'Relevel Default Queue'
                          limit 1].Id;
        String QueryString = 'SELECT AO_Interview_Status_Manual__c,Email,Id,Interview_Id__c,isActive__c,Is_Interview_Conducted__c,LastName,Lead_Version__c,Name,Offer_Status__c,OwnerId,Phone_formatted__c FROM Lead Where AO_Interview_Status_Manual__c != Null And Lead_Version__c = \'V1\' and OwnerId !=: queueId';
        return Database.getQueryLocator(QueryString);
        
    }

    public void execute(Database.BatchableContext bc, List<Lead> LeadList){
        string queueId = [SELECT Id, Type
                          FROM Group
                          WHERE Type = 'Queue' AND Name = 'Relevel Default Queue'
                          limit 1].Id;
         string noShowQueueId = [SELECT Id, Type
                          FROM Group
                          WHERE Type = 'Queue' AND Name = 'NO Show Queue'
                          limit 1].Id;
        System.debug('queueId =====> ' + queueId);
        List<Lead> UpdatedLeadList = new List<Lead>();
        if (!LeadList.isEmpty()) {
            for (Lead Ld : LeadList) {
                if (ld.Lead_Version__c == 'V1' && ld.AO_Interview_Status_Manual__c != null && (ld.AO_Interview_Status_Manual__c == 'Learner No-Show' || ld.AO_Interview_Status_Manual__c =='AO No-Show') && ld.OwnerId != queueId) {
                    ld.OwnerId = noShowQueueId;
                    ld.Lead_Stage__c = 'Unassigned';
                    UpdatedLeadList.add(ld);
                }  
            }
        }
        if (!UpdatedLeadList.isEmpty()) {
            update UpdatedLeadList;
        }
    }
    public void finish(Database.BatchableContext bc){
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors,
                            JobItemsProcessed,
                            TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];

    }
}