force-app/main/default/objects/Lead/fields/Birth_Year__c.field-meta.xml
<CustomField>
    <fullName>Birth_Year__c</fullName>
    <label>Birth Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Goal_Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Goal_Interested_In__c</fullName>
    <label>Course Interested In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
            </value>
            <value>
                <fullName>HR-Generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
                <label>Operations-Associate</label>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_status__c.field-meta.xml
<CustomField>
    <fullName>Lead_status__c</fullName>
    <label>Lead status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Payment Made</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>Not Contact</fullName>
            </value>
            <value>
                <fullName>No access to desktop/laptop</fullName>
            </value>
            <value>
                <fullName>Cannot understand English</fullName>
            </value>
            <value>
                <fullName>Just Checking Details</fullName>
            </value>
            <value>
                <fullName>Joined/Will join competitor</fullName>
            </value>
            <value>
                <fullName>Fee is High</fullName>
            </value>
            <value>
                <fullName>Next Batch</fullName>
            </value>
            <value>
                <fullName>Professionally Busy</fullName>
            </value>
            <value>
                <fullName>Personal Reason</fullName>
            </value>
            <value>
                <fullName>Travelling Abroad / Onsite</fullName>
            </value>
            <value>
                <fullName>Looking for another Program</fullName>
            </value>
            <value>
                <fullName>Enrolled for another Program with us</fullName>
            </value>
            <value>
                <fullName>Did not Enquire</fullName>
            </value>
            <value>
                <fullName>Looking for WFH jobs</fullName>
            </value>
            <value>
                <fullName>Do not have laptop/desktop</fullName>
            </value>
            <value>
                <fullName>Can not understand English</fullName>
            </value>
            <value>
                <fullName>Can not pay 1st EMI as well</fullName>
            </value>
            <value>
                <fullName>Loan Rejected</fullName>
            </value>
            <value>
                <fullName>Work Experience</fullName>
            </value>
            <value>
                <fullName>Age Bar</fullName>
            </value>
            <value>
                <fullName>Poor Communication</fullName>
            </value>
            <value>
                <fullName>Not a Graduate</fullName>
            </value>
            <value>
                <fullName>Score is low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Leads_Age__c.field-meta.xml
<CustomField>
    <fullName>Leads_Age__c</fullName>
    <formula>TODAY() - Lead_Assigned_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leads Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Learner_Uid__c.field-meta.xml
<CustomField>
    <fullName>Learner_Uid__c</fullName>
    <defaultValue>&quot;CTI&quot;</defaultValue>
    <label>Learner Uid</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source_Intent__c.field-meta.xml
<CustomField>
    <fullName>Source_Intent__c</fullName>
    <label>Source Intent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
                <label>data-analytics</label>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
                <label>associate-product-management</label>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
                <label>business-analytics</label>
            </value>
            <value>
                <fullName>android-development</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
            </value>
            <value>
                <fullName>hr-generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
            <value>
                <fullName>Front-End</fullName>
                <isActive>false</isActive>
                <label>Front-End</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadReassignmentBatch.cls
public class LeadReassignmentBatch implements Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext BC){
        if(test.isRunningTest()){
           return Database.getQueryLocator([SELECT Id,OwnerId,Goal_Interested_In__c,Source_Intent__c,LeadSource,Learner_Uid__c,Company,FirstName,LastName,Email,Age__c,Birth_Year__c,Phone ,Experience__c,Country,State From Lead Where Lead_status__c = 'Not Contact' ]); 
        }else{
         return Database.getQueryLocator([SELECT Id,OwnerId,Goal_Interested_In__c,Source_Intent__c,LeadSource,Learner_Uid__c,Company,FirstName,LastName,Email,Age__c,Birth_Year__c,Phone ,Experience__c,Country,State From Lead Where Leads_Age__c >= 15 AND Lead_status__c = 'Not Contact' ]);   
        }
        
    }
    public void execute(Database.BatchableContext BC, List<Lead> leadsToBeReassigned){
        string goalIntrestedIn = '';
        Map<String, string> leadOwnerIdByLeadId = new Map<String, String>();
        List<Lead> clonnedLeadsToBeInserted = new List<Lead>();
        List<Lead> clonnedLeadsToBeUpdated = new List<Lead>();
        List<Id> leadsToBeDeleted = new List<Id>();
        List<Id> clonnedLeadsIdToBeUpdated = new List<Id>();
        list<task> leadTaskTobeDelete = new list<task>();
        string queueId = [SELECT Id, Type FROM Group WHERE Type = 'Queue' AND Name = 'Relevel Default Queue'].Id;
        system.debug('leadsToBeReassigned::'+leadsToBeReassigned);
        if(!leadsToBeReassigned.isEmpty()){
            for(Lead leadRec : leadsToBeReassigned){
                goalIntrestedIn = leadRec.Goal_Interested_In__c;
                leadOwnerIdByLeadId.put(leadRec.Id, leadRec.OwnerId);
                lead clonnedLead = new lead();
                clonnedLead = leadRec.clone();
                clonnedLead.Learner_Uid__c = leadRec.Learner_Uid__c+'UID'+leadRec.OwnerId;
                clonnedLead.OwnerId = queueId;
                clonnedLeadsToBeInserted.add(clonnedLead);
                leadsToBeDeleted.add(leadRec.Id);
            }
            
            leadTaskTobeDelete = [select id from task where whoid in: leadsToBeDeleted];
            system.debug('leadOwnerIdByLeadId::'+leadOwnerIdByLeadId);
            system.debug('clonnedLeadsToBeInserted::'+clonnedLeadsToBeInserted);
            system.debug('leadsToBeDeleted::'+leadsToBeDeleted);
            
            Database.SaveResult[] srList = Database.insert(clonnedLeadsToBeInserted, false);
            system.debug('srList::'+srList);
            for(Database.SaveResult sr : srList){
                if(sr.isSuccess()){
                    clonnedLeadsIdToBeUpdated.add(sr.getId());
                }
            }
            system.debug('clonnedLeadsIdToBeUpdated::'+clonnedLeadsIdToBeUpdated);
            if(!clonnedLeadsIdToBeUpdated.isEmpty()){
                RoundRobinLeadAssignment.assignLeadsToBDS(goalIntrestedIn);
                database.delete(leadsToBeDeleted);
                database.delete(leadTaskTobeDelete);
                clonnedLeadsToBeUpdated = [Select Id,Learner_Uid__c From Lead Where Id In: clonnedLeadsIdToBeUpdated];
                system.debug('clonnedLeadsToBeUpdated::'+clonnedLeadsToBeUpdated);
                if(!clonnedLeadsToBeUpdated.isEmpty()){
                    for(Lead updateLearnerUID : clonnedLeadsToBeUpdated){
                        system.debug('updateLearnerUID::'+updateLearnerUID);
                        integer index = updateLearnerUID.Learner_Uid__c.indexOf('UID');
                        system.debug('index::'+index);
                        updateLearnerUID.Learner_Uid__c = updateLearnerUID.Learner_Uid__c.substring(0, index);
                        system.debug('updateLearnerUID.Learner_Uid__c::'+updateLearnerUID.Learner_Uid__c);
                    }
                    system.debug('clonnedLeadsToBeUpdated::'+clonnedLeadsToBeUpdated);
                    Update clonnedLeadsToBeUpdated; 
                }
            }
        }
    }
    
    public void finish(Database.BatchableContext BC){
    }
}