force-app/main/default/objects/Lead/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Mechanical</fullName>
            </value>
            <value>
                <fullName>Civil</fullName>
            </value>
            <value>
                <fullName>CS &amp; IT</fullName>
            </value>
            <value>
                <fullName>Instrumentation</fullName>
            </value>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>Biotech</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Arts</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Paramedical</fullName>
            </value>
            <value>
                <fullName>Vocational Courses</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Science</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Law</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Mass Communications</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Computer Applications</fullName>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
            <value>
                <fullName>Architecture</fullName>
            </value>
            <value>
                <fullName>Hotel Management</fullName>
            </value>
            <value>
                <fullName>Animation</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Veterinary Sciences</fullName>
            </value>
            <value>
                <fullName>Aviation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <label>Follow Up Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Goal_Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Goal_Interested_In__c</fullName>
    <label>Course Interested In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
            </value>
            <value>
                <fullName>HR-Generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
                <label>Operations-Associate</label>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Pitched__c.field-meta.xml
<CustomField>
    <fullName>Loan_Pitched__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Loan Pitched</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Lead Validation Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DispositionFormHelper.cls
public class DispositionFormHelper {
    @auraEnabled
    public static Lead fetchLead(String leadId){
        Lead leadRec = new Lead();
        
        if(!string.isBlank(leadId)){
           // leadRec = [ Select Id,Goal_Interested_In__c,Notes__c,Goal_Name__c,Follow_Up_Date__c,Loan_Pitched__c,Branch__c,Loan_Link_Sent__c From Lead Where Id =: leadId];
            system.debug('leadRec::'+leadRec);
            return leadRec;
        }else{
            return null;
        }      
    }
    @auraEnabled
    public static void updateLeadData(Lead leadRec){
        try{
            update leadRec;
        }catch(Exception ex){
            system.debug('Error::>'+ex.getMessage());
            system.debug('Error::>'+ex.getLineNumber());
        }    
    }
    @AuraEnabled
    public static List<String> getPickListValuesIntoList(String strObjectName, String strPicklistField){
        system.debug('strObjectName::'+strObjectName);
        system.debug('strPicklistField::'+strPicklistField);
        List<String> pickListValuesList= new List<String>();
        Map<String, String> mapPickListValues = new Map<String, String>();
        Schema.SObjectType objSobjectType = Schema.getGlobalDescribe().get(strObjectName);
        Schema.DescribeSObjectResult objDescribeSobject = objSobjectType.getDescribe();
        Map<String, Schema.SObjectField> mapFields = objDescribeSobject.fields.getMap();
        List<Schema.PicklistEntry> lstPickListValues = mapFields.get(strPicklistField).getDescribe().getPickListValues();
        for( Schema.PicklistEntry pickListVal : lstPickListValues){
            pickListValuesList.add(pickListVal.getLabel());
        }     
        system.debug('pickListValuesList::>'+pickListValuesList);
        return pickListValuesList;
    }
    
    @auraEnabled 
    public static Map<String,List<String>> getAllPickValues(string objectName){
       
        Map<String,Map<String,List<String>>> pickListValuesByFieldNameByObjName = new Map<String,Map<String,List<String>>>();
        Map<String , Schema.SObjectType> schemaGlobalDescription = Schema.getGlobalDescribe();
        Map<String , Schema.SObjectField> mapFieldList = new Map<String , Schema.SObjectField>();
        Map<String,List<String>> picklistValuesByFieldName = new Map<String,List<String>>();
       
            SObjectType sObjType = ((SObject) Type.forName(objectName).newInstance()).getSObjectType();
            Map <String, Schema.SObjectField> fieldMap = sObjType.getDescribe().fields.getMap();
            
            system.debug('fieldMap::'+fieldMap);
            for(string fieldName : fieldMap.keySet()){ //FieldName
                
                String fieldLabel = fieldMap.get(fieldName).getDescribe().getLabel();
                Schema.DisplayType fielddataType = fieldMap.get(fieldName).getDescribe().getType();
                
                if(fielddataType == Schema.DisplayType.Picklist){ //DataType of field
                    
                    List<Schema.PicklistEntry> pick_list_values = sObjType.getDescribe().fields.getMap().get(fieldName).getDescribe().getPickListValues(); // picklist values of field
                    List<String> picklistValues = new List<String>();
                    
                    for (Schema.PicklistEntry aPickListValue : pick_list_values) {                   
                        picklistValues.add(aPickListValue.getValue()); 
                    }
                    picklistValuesByFieldName.put(fieldMap.get(fieldName).getDescribe().getLabel(),picklistValues);                 
                }               
            }
        system.debug('picklistValuesByFieldName::'+picklistValuesByFieldName);
        return picklistValuesByFieldName;
    }
}