force-app/main/default/objects/Lead/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <label>Follow Up Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Goal_Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Goal_Interested_In__c</fullName>
    <label>Course Interested In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
            </value>
            <value>
                <fullName>HR-Generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
                <label>Operations-Associate</label>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_status__c.field-meta.xml
<CustomField>
    <fullName>Lead_status__c</fullName>
    <label>Lead status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
            <value>
                <fullName>Payment Made</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>Not Contact</fullName>
            </value>
            <value>
                <fullName>No access to desktop/laptop</fullName>
            </value>
            <value>
                <fullName>Cannot understand English</fullName>
            </value>
            <value>
                <fullName>Just Checking Details</fullName>
            </value>
            <value>
                <fullName>Joined/Will join competitor</fullName>
            </value>
            <value>
                <fullName>Fee is High</fullName>
            </value>
            <value>
                <fullName>Next Batch</fullName>
            </value>
            <value>
                <fullName>Professionally Busy</fullName>
            </value>
            <value>
                <fullName>Personal Reason</fullName>
            </value>
            <value>
                <fullName>Travelling Abroad / Onsite</fullName>
            </value>
            <value>
                <fullName>Looking for another Program</fullName>
            </value>
            <value>
                <fullName>Enrolled for another Program with us</fullName>
            </value>
            <value>
                <fullName>Did not Enquire</fullName>
            </value>
            <value>
                <fullName>Looking for WFH jobs</fullName>
            </value>
            <value>
                <fullName>Do not have laptop/desktop</fullName>
            </value>
            <value>
                <fullName>Can not understand English</fullName>
            </value>
            <value>
                <fullName>Can not pay 1st EMI as well</fullName>
            </value>
            <value>
                <fullName>Loan Rejected</fullName>
            </value>
            <value>
                <fullName>Work Experience</fullName>
            </value>
            <value>
                <fullName>Age Bar</fullName>
            </value>
            <value>
                <fullName>Poor Communication</fullName>
            </value>
            <value>
                <fullName>Not a Graduate</fullName>
            </value>
            <value>
                <fullName>Score is low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Learner_Uid__c.field-meta.xml
<CustomField>
    <fullName>Learner_Uid__c</fullName>
    <defaultValue>&quot;CTI&quot;</defaultValue>
    <label>Learner Uid</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source_Intent__c.field-meta.xml
<CustomField>
    <fullName>Source_Intent__c</fullName>
    <label>Source Intent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
                <label>data-analytics</label>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
                <label>associate-product-management</label>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
                <label>business-analytics</label>
            </value>
            <value>
                <fullName>android-development</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
            </value>
            <value>
                <fullName>hr-generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
            <value>
                <fullName>Front-End</fullName>
                <isActive>false</isActive>
                <label>Front-End</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
                <default>true</default>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadTriggerHandlerTest.cls
@isTest
public without sharing class LeadTriggerHandlerTest {

    
    @isTest
    public static void LeadTriggerTest(){
        wk_exo__Exotel_Configuration__c testExotel = new wk_exo__Exotel_Configuration__c();
        testExotel.wk_exo__By_Default_Create__c = 'Lead';
        testExotel.wk_exo__SID__c = '12345';
        testExotel.wk_exo__Masking_Character__c = '*';
        testExotel.wk_exo__Number_of_Digits__c = '11';
        testExotel.wk_exo__Record_Type__c = 'test';
        insert testExotel;
        Group testGroup = new Group(Name='Relevel Default Queue', Type='Queue');
        insert testGroup;
        
        
        Lead leads= new Lead();
        leads.FirstName ='test first name';
        leads.LastName='Test last name';
        leads.Company='test';
        leads.Learner_Uid__c='test';
        leads.Source_Intent__c='Backend-Development';
        leads.Temperature__c = 'Hot';
        leads.Follow_Up_Date__c=Date.today();
        leads.Goal_Interested_In__c = 'Business-Development';
        leads.Lead_status__c = 'New';
        //leads.OwnerId=testGroup.Id;
        List<Lead> listLead=new List<Lead>();
        listLead.add(leads);
        
        test.startTest();
        
        insert listLead;
        LeadTriggerHandler.assignDefaultQueue(listLead);
        LeadTriggerHandler.runLeadAssignment(listLead);
        
        List<Lead> listofLead=new List<Lead>();
        leads.Follow_Up_Date__c=Date.today().addDays(2);
        listofLead.add(leads);
        update listofLead;
        
        Map<Id,Lead> leadsMap=new Map<Id,Lead>(listLead);
        System.debug(leadsMap);
        Map<Id,Lead> newleadsMap=new Map<Id,Lead>(listofLead);
        System.debug(newleadsMap);
        System.debug(leadsMap);
        LeadTriggerHandler.insertFollowUpTask(newleadsMap,leadsMap);// (leadsMap,newleadsMap);
        LeadTriggerHandler.updateFollowUpCount(leadsMap,newleadsMap);
        LeadTriggerHandler.updateStageAsClosure(leadsMap,newleadsMap);
        test.stopTest();
        
        Lead Leadrec = [Select Id,Lead_status__c From Lead limit 1] ;
        Leadrec.Lead_status__c = 'non-contact';
        Leadrec.Goal_Interested_In__c = 'Frontend-Development';
        update LeadRec;
        
    }
}