force-app/main/default/objects/Lead/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <label>Follow Up Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Goal_Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Goal_Interested_In__c</fullName>
    <label>Course Interested In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
            </value>
            <value>
                <fullName>HR-Generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
                <label>Operations-Associate</label>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
            <value>
                <fullName>Conducted</fullName>
            </value>
            <value>
                <fullName>Offer Rolled Out</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Called</fullName>
            </value>
            <value>
                <fullName>Nurturing</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Learner_Uid__c.field-meta.xml
<CustomField>
    <fullName>Learner_Uid__c</fullName>
    <defaultValue>&quot;CTI&quot;</defaultValue>
    <label>Learner Uid</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Payment_details__c.field-meta.xml
<CustomField>
    <fullName>Payment_details__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Payment details</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source_Intent__c.field-meta.xml
<CustomField>
    <fullName>Source_Intent__c</fullName>
    <label>Source Intent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
                <label>data-analytics</label>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
                <label>associate-product-management</label>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
                <label>business-analytics</label>
            </value>
            <value>
                <fullName>android-development</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
            </value>
            <value>
                <fullName>hr-generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
            <value>
                <fullName>Front-End</fullName>
                <isActive>false</isActive>
                <label>Front-End</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
                <default>true</default>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestUtility.cls
@isTest
public class TestUtility {
    public static List<Lead> createTestData(){
        List<Lead> listLead=new List<Lead>();
        for(Integer i=0;i<10;i++)
        {
            Lead leads=new Lead();
            leads.Lead_Assigned_Date__c = Date.today();
            leads.FirstName='test'+i;
            leads.LastName='Last Name'+i;
            leads.Source_Intent__c='Backend-Development';
            leads.Goal_Interested_In__c='FrontEnd-Development';
            leads.Company='test'+i;
            leads.Learner_Uid__c='test'+i;
            leads.Payment_details__c=2.0;
            leads.Learner_Uid__c='test UID';
            leads.Temperature__c = 'Hot';
            leads.Lead_Stage__c='New';
            listLead.add(leads);
        }
        insert listLead;
        System.debug(listLead);
        return listLead;
    }
    
    public static List<Task> createTestTask(){
        List<Task> listTask=new List<Task>();
        for(Integer i=0;i<10;i++){
            Task taskData=new Task();
            taskData.Subject='Test '+i;
            taskData.Description='Test '+i;
            // taskData.wk_exo__call_end_time__c=string.valueof( DateTime.newInstance(2021,1, i+1, 3, 3, 3));
            taskData.wk_exo__call_start_time__c=string.valueof( DateTime.newInstance(2021,1, i+1, 3, 3, 3));
            listTask.add(taskData);
        }
        insert listTask;
        return listTask;
    }
    public static Lead createLead(){
        Lead leadRec = new Lead();
        leadRec.FirstName ='test first name';
        leadRec.LastName='Test last name';
        leadRec.Company='test';
        leadRec.phone='01234567891';
        leadRec.Learner_Uid__c='test';
        leadRec.Source_Intent__c='Backend-Development';
        leadRec.Goal_Interested_In__c='FrontEnd-Development';
        leadRec.Follow_Up_Date__c=Date.today();
        leadRec.Email = 'aakash.jain@mailinator.com';
        //leads.OwnerId=testGroup.Id;
        return leadRec;
    }
    public static void insertUserInfo(String firstName, String LastName, String Email, String userName, Boolean isActive,String managerId){
        
        List<Profile> profileList = [Select Id,Name From Profile Where Name =: system.label.BDE_Profile_Name OR Name = 'Sales Manager' OR Name = 'Senior Sales Manager'];
        System.debug('profileList::'+profileList);
        List<User> userList = new List<User>();
    }
}