force-app/main/default/objects/Lead/fields/Goal_Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Goal_Interested_In__c</fullName>
    <label>Course Interested In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
            </value>
            <value>
                <fullName>HR-Generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
                <label>Operations-Associate</label>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Learner_Uid__c.field-meta.xml
<CustomField>
    <fullName>Learner_Uid__c</fullName>
    <defaultValue>&quot;CTI&quot;</defaultValue>
    <label>Learner Uid</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source_Intent__c.field-meta.xml
<CustomField>
    <fullName>Source_Intent__c</fullName>
    <label>Source Intent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
                <label>data-analytics</label>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
                <label>associate-product-management</label>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
                <label>business-analytics</label>
            </value>
            <value>
                <fullName>android-development</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
            </value>
            <value>
                <fullName>hr-generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
            <value>
                <fullName>Front-End</fullName>
                <isActive>false</isActive>
                <label>Front-End</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchTODeleteLeadTesr.cls
@isTest public class BatchTODeleteLeadTesr {
    
    @isTest Public static void deletingLeads(){
        wk_exo__Exotel_Configuration__c wkExo = new wk_exo__Exotel_Configuration__c();
        insert wkExo;
        Lead ld = new Lead();
        ld.LastName ='Test';
        ld.Company = 'Util';
        ld.Phone='0911234567892';
        ld.Goal_Interested_In__c = 'Data-Analytics';
        ld.Source_Intent__c = 'Data-Analytics';
        ld.Learner_Uid__c = 'CAN-!12214234';
        insert ld;
        BatchToDeleteAllLeads batchInstanc = new BatchToDeleteAllLeads();
        database.executeBatch(batchInstanc);
    }
}