force-app/main/default/objects/Lead/fields/Goal_Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Goal_Interested_In__c</fullName>
    <label>Course Interested In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
            </value>
            <value>
                <fullName>HR-Generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
                <label>Operations-Associate</label>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Learner_Uid__c.field-meta.xml
<CustomField>
    <fullName>Learner_Uid__c</fullName>
    <defaultValue>&quot;CTI&quot;</defaultValue>
    <label>Learner Uid</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadReassignmentHelper.cls
public without sharing class LeadReassignmentHelper {
    @auraEnabled
    public static void updateLeadDetails(string leadRec){
        try{
               system.debug('leadRec::'+leadRec);
        if(!String.isBlank(leadRec)){
            Lead leadRecToBeUpdated = [Select id,OwnerId,Learner_Uid__c from Lead Where Id = : leadRec];
            system.debug('lead.Goal ::'+leadRecToBeUpdated.OwnerId );
            string queueId = [SELECT Id, Type FROM Group WHERE Type = 'Queue' AND Name = 'Relevel Default Queue' limit 1].Id;
            system.debug('queueId::'+queueId);
            leadRecToBeUpdated.OwnerId = queueId;
            update leadRecToBeUpdated;
            system.debug('lead.Goal ::'+leadRecToBeUpdated.OwnerId);
            String courseInterested = [Select Goal_Interested_In__c From Lead Where Id =: leadRec limit 1].Goal_Interested_In__c;
            if(!String.isBlank(courseInterested)){
                RoundRobinLeadAssignment.assignLeadsToBDS(courseInterested);
            }
        } 
        }catch(exception ex){
            system.debug('Error>>'+ex.getMessage());
            system.debug('Err@@>>'+ex.getLineNumber());
                
        }
    
    }    
}