force-app/main/default/objects/Lead/fields/Goal_Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Goal_Interested_In__c</fullName>
    <label>Course Interested In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
            </value>
            <value>
                <fullName>HR-Generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
                <label>Operations-Associate</label>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Source_Intent__c.field-meta.xml
<CustomField>
    <fullName>Source_Intent__c</fullName>
    <label>Source Intent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
                <label>data-analytics</label>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
                <label>associate-product-management</label>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
                <label>business-analytics</label>
            </value>
            <value>
                <fullName>android-development</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
            </value>
            <value>
                <fullName>hr-generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
            <value>
                <fullName>Front-End</fullName>
                <isActive>false</isActive>
                <label>Front-End</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchToTransferLeadFromDeactUserTest.cls
@isTest
public class BatchToTransferLeadFromDeactUserTest {
    
    @testSetup
    static void setup() {
        List<Lead> LeadList = new List<Lead>();
        for(integer i=0; i<10; i++){
            Lead newLeadRec = new Lead();		//Company,LastName,status, Goal_Interested_In__c, Source_Intent__c
            newLeadRec.Company = 'Utilab '+i;
            newLeadRec.LastName = 'Jackson ' +i; 
            newLeadRec.Status = 'Follow-up';
            newLeadRec.Source_Intent__c = 'Business-Development';
            newLeadRec.Goal_Interested_In__c = 'Frontend-Development';
            LeadList.add(newLeadRec);
        }
        insert LeadList;
    }
    
    @isTest static void test() {
        Test.startTest();
        BatchToTransferLeadFromDeactivatedUser uca = new BatchToTransferLeadFromDeactivatedUser();
        Id batchId = Database.executeBatch(uca);
        Test.stopTest();
        // after the testing stops, assert records were updated properly
        //System.assertEquals(10, [select count() from contact where MailingCity = 'New York']);
    }

}