force-app/main/default/objects/Lead/fields/Interview_Status_AO__c.field-meta.xml
<CustomField>
    <fullName>Interview_Status_AO__c</fullName>
    <label>Interview Status (AO)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Conducted</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>No Conducted</fullName>
                <label>Not Conducted</label>
            </value>
            <value>
                <fullName>AO No Show</fullName>
                <isActive>false</isActive>
                <label>AO No Show</label>
            </value>
            <value>
                <fullName>No Show</fullName>
                <isActive>false</isActive>
                <label>No Show</label>
            </value>
            <value>
                <fullName>Partial Conducted</fullName>
                <isActive>false</isActive>
                <label>Partial Conducted</label>
            </value>
            <value>
                <fullName>Refer notes</fullName>
                <isActive>false</isActive>
                <label>Refer notes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Interview_Sub_Status_AO__c.field-meta.xml
<CustomField>
    <fullName>Interview_Sub_Status_AO__c</fullName>
    <label>Interview Sub-Status (AO)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interview_Status_AO__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Learner - No Show</fullName>
            </value>
            <value>
                <fullName>AO - No Show</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Wrong Schedule Conducted by AC</fullName>
            </value>
            <value>
                <fullName>Scheduled outside working hours</fullName>
            </value>
            <value>
                <fullName>Logistics - Laptop/Internet Issue</fullName>
            </value>
            <value>
                <fullName>Learner not prepared/not ready</fullName>
            </value>
            <value>
                <fullName>Incorrect/False Schedule</fullName>
            </value>
            <value>
                <fullName>Expectation Mismatch (4Ps)</fullName>
            </value>
            <value>
                <fullName>Not Interested/ Mind Changed</fullName>
            </value>
            <value>
                <fullName>System Challenges</fullName>
            </value>
            <value>
                <fullName>Under Prepared</fullName>
            </value>
            <value>
                <fullName>Rescheduled by Learner</fullName>
            </value>
            <value>
                <fullName>AO Requested for reschedule</fullName>
            </value>
            <value>
                <fullName>Learner was not prepared</fullName>
            </value>
            <value>
                <fullName>Erroneous Schedule</fullName>
            </value>
            <value>
                <fullName>Time slot miss Match</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateLeadInterviewStatusBasedOnEvtDesc.cls
public class UpdateLeadInterviewStatusBasedOnEvtDesc {
    
    public static void GetEventDescriptionDetails( Map<String,String> evtMap, String leadId){
      try {
        Integer Relevelcount = 0;
        Integer GmailCount = 0;
        //integer
        List<Lead> LeadListToUpdate = new List<Lead>();
        Lead leadRec = [SELECT Id,Interview_Status_AO__c, Interview_Sub_Status_AO__c FROM Lead WHERE Id =:leadId ];
        
        
        for(String evt : evtMap.keySet()){
            String evtupdated = (evt != NULL ||  evt != 'NULL') ? evt : '';
            System.debug('evtupdated =====> ' + evtupdated); 
            if (evt != null) {
                if(evt.contains('@relevel.com') ){
                    Relevelcount ++;                
                } else if(evt.contains('@gmail.com') ){ 
                    GmailCount ++;         
                }
                else{
                    GmailCount ++;
                }
            }
            else{
                if(String.valueOf(evt) == 'null'){
                    GmailCount ++; 
                }
            }
            
        }
        if(GmailCount > 0 && Relevelcount > 0){
            leadRec.Interview_Status_AO__c = 'Conducted';
        }
        else{
            if(GmailCount == 0 && Relevelcount > 0){
                leadRec.Interview_Status_AO__c = 'No Conducted';
                leadRec.Interview_Sub_Status_AO__c = 'Learner - No Show';
            }else if(GmailCount > 0 && Relevelcount == 0){
                leadRec.Interview_Status_AO__c = 'No Conducted';
                leadRec.Interview_Status_AO__c = 'AO No Show';

            }
        }
        //else if(GmailCount > 0 && Relevelcount == 0 ){
        //    leadRec.Interview_Status_AO__c = 'AO No Show';
        //}

        update leadRec;
        
      } catch (Exception e) {
        System.debug('Error message :; ' + e.getMessage() + ' at line number :: ' + e.getLineNumber());
      }
        
    }
}