force-app/main/default/objects/Lead/fields/Interview_Date_Time_AC__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date_Time_AC__c</fullName>
    <label>Interview Date/Time (AC)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Interview_Slot_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Interview_Slot_Date_Time__c</fullName>
    <label>Interview Slot Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Interview_Type__c.field-meta.xml
<CustomField>
    <fullName>Interview_Type__c</fullName>
    <label>Interview Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Now</fullName>
            </value>
            <value>
                <fullName>Later</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/IVR_Called__c.field-meta.xml
<CustomField>
    <fullName>IVR_Called__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IVR Called</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Version__c.field-meta.xml
<CustomField>
    <fullName>Lead_Version__c</fullName>
    <label>Lead Version</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V0</fullName>
            </value>
            <value>
                <fullName>V1</fullName>
                <default>true</default>
                <label>V1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SID__c.field-meta.xml
<CustomField>
    <fullName>SID__c</fullName>
    <label>SID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Slot_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Slot_DateTime__c</fullName>
    <formula>DATETIMEVALUE( TEXT( Interview_Date__c ) + &quot; &quot; +   
IF( SUBSTITUTE(LEFT( Interview_slot__c , 8), LEFT( Interview_slot__c , 6), &apos;&apos;) == &apos;AM&apos;  ,
 LEFT( Interview_slot__c , 2), 
 if(LEFT( Interview_slot__c , 2) == &apos;12&apos;, LEFT( Interview_slot__c , 2),TEXT(VALUE(LEFT( Interview_slot__c , 2))+12))) 
 
 
 + &apos;:&apos; + SUBSTITUTE(LEFT( Interview_slot__c , 5), LEFT( Interview_slot__c , 3), &apos;&apos;) 
  + &apos;:&apos; + &apos;00&apos;  )  - 33/144</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Slot DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CallExotelApi.cls
global class CallExotelApi implements Schedulable
{
    global void execute(SchedulableContext ctx)
    {
        DateTime systemNow = System.now();
        DateTime thirtyFiveMins = System.now().addMinutes(35);
        
        String query = 'SELECT id,Name,Phone,Email,SID__c,Interview_Date_Time_AC__c,IVR_Called__c,OwnerId,Interview_Slot_Date_Time__c FROM Lead WHERE ((Interview_Date_Time_AC__c >: systemNow AND Interview_Date_Time_AC__c <: thirtyFiveMins) OR (Slot_DateTime__c >: systemNow AND Slot_DateTime__c <: thirtyFiveMins AND Lead_Version__c = \'V1\' AND Interview_Type__c	= \'Later\')) AND IVR_Called__c = false AND Phone != null limit 40000';
        List<Lead> LeadList =  Database.query(query);
        
        if(!LeadList.isEmpty()){
            System.enqueueJob(new AsyncHelperForIVR(LeadList,0,1));
        }
    }
}