force-app/main/default/objects/Lead/fields/Interview_Date_Time_AC__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date_Time_AC__c</fullName>
    <label>Interview Date/Time (AC)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/IVR_Called__c.field-meta.xml
<CustomField>
    <fullName>IVR_Called__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IVR Called</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchForIVRAsync.cls
global  class BatchForIVRAsync implements Database.Batchable<sObject> , Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext BC) {
        DateTime thirtyMins = System.now().addMinutes(25);
        DateTime thirtyFiveMins = System.now().addMinutes(35);
        
        String query = 'SELECT id,Name,Phone,Email,Interview_Date_Time_AC__c,IVR_Called__c,OwnerId FROM Lead WHERE Interview_Date_Time_AC__c >: thirtyMins AND Interview_Date_Time_AC__c <: thirtyFiveMins AND IVR_Called__c = false AND Phone != null';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Lead> leadList){
        List<Lead> leadListToBeUpdated = new List<Lead>();
        
        for(Lead leadRec : leadList){
            HelperForIVRAsync.ExotelCallout(leadRec.Id);
        }
    }
    
    public void finish(Database.BatchableContext BC) {
    }  
    
}