force-app/main/default/objects/Lead/fields/isQualityScoreUpdated__c.field-meta.xml
<CustomField>
    <fullName>isQualityScoreUpdated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isQualityScoreUpdated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Quality_Score__c.field-meta.xml
<CustomField>
    <fullName>Quality_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quality Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quality_Score__c/Quality_Score__c.object-meta.xml
<CustomObject>
    <label>Quality Score</label>
    <nameField>
        <displayFormat>QA-{0000000}</displayFormat>
        <label>Quality Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Score</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Score__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Quality Score</relationshipLabel>
    <relationshipName>Quality_Score</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quality_Score__c/fields/Quality_Score__c.field-meta.xml
<CustomField>
    <fullName>Quality_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quality Score</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchToUpdateQScoreOnLead.cls
public class BatchToUpdateQScoreOnLead implements
Database.Batchable<sObject>, Database.Stateful {
    // instance member to retain state across transactions
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String QueryString = 'SELECT Id,Lead__c,Name,Quality_Score__c FROM Quality_Score__c where Lead__c !=null';
        return Database.getQueryLocator(QueryString);
    }
    public void execute(Database.BatchableContext bc, List<Quality_Score__c> QScoreList){
        // process each batch of records
        map<String, Quality_Score__c> LeadIdWithQualityScore = new map<String, Quality_Score__c>();
        set<Id> LeadIdlist = new set<Id>();
        List<Lead> LeadListToBeFetched = new List<Lead>();
        List<Lead> LeadListToBeUpdated = new List<Lead>();
        
        if(!QScoreList.isEmpty()){
            for(Quality_Score__c Qscore : QScoreList){
                LeadIdWithQualityScore.put(Qscore.Lead__c, Qscore);
                LeadIdlist.add(Qscore.Lead__c);
            }
            if(!LeadIdlist.isEmpty()){
                LeadListToBeFetched = [SELECT Id, name, Quality_Score__c FROM Lead where Id IN: LeadIdlist and (Quality_Score__c = null OR Quality_Score__c = 0)];
                system.debug('LeadListToBeFetched :: ' + LeadListToBeFetched);
            }
            if(!LeadListToBeFetched.isEmpty()){
                for(Lead ld : LeadListToBeFetched){
                    lead updatedlead = new Lead();
                    updatedlead.Id = ld.id;
                    updatedlead.isQualityScoreUpdated__c = true;
                    updatedlead.Quality_Score__c = LeadIdWithQualityScore.get(ld.id).Quality_Score__c;
                    LeadListToBeUpdated.add(updatedlead);
                }
            }
            if(!LeadListToBeUpdated.isEmpty()){
                update LeadListToBeUpdated;
            }
        }
        
        
    }
    public void finish(Database.BatchableContext bc){
        
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors,
                            JobItemsProcessed,
                            TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];
        // call some utility to send email
        //EmailUtils.sendMessage(job, recordsProcessed);
    }
    
}