force-app/main/default/objects/Lead/fields/Lead_Version__c.field-meta.xml
<CustomField>
    <fullName>Lead_Version__c</fullName>
    <label>Lead Version</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>V0</fullName>
            </value>
            <value>
                <fullName>V1</fullName>
                <default>true</default>
                <label>V1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Updated_Lead_Version__c.field-meta.xml
<CustomField>
    <fullName>Updated_Lead_Version__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updated Lead Version</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchForUpdatingLeadVersion.cls
public class BatchForUpdatingLeadVersion implements Database.Batchable<sObject>{
    public static final string IdLeadOldFlowRT = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Old Flow').getRecordTypeId();
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'select id,Lead_Version__c,recordTypeId,Updated_Lead_Version__c From Lead where Updated_Lead_Version__c = false';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Lead> leadList){
        List<Lead> leadListToUpdate = new List<Lead>();
        
        for(Lead leadRec : leadList){
            Lead LeadRecToUpdate = new Lead();
            LeadRecToUpdate.Id = leadRec.Id;
            LeadRecToUpdate.RecordTypeId = IdLeadOldFlowRT; 
            LeadRecToUpdate.Lead_Version__c = 'V0';
            LeadRecToUpdate.Updated_Lead_Version__c = true;
            leadListToUpdate.add(LeadRecToUpdate);
        }
        if(!leadListToUpdate.isEmpty()){
            update leadListToUpdate;
        }
    }
    public void finish(Database.BatchableContext BC) {
    }  
}