force-app/main/default/objects/Lead/fields/Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>Offer_Status__c</fullName>
    <formula>IF( ISPICKVAL(Profession__c,&apos;&apos;) || ISPICKVAL(Communication__c , &apos;&apos;) || ISPICKVAL(Intent__c, &apos;&apos; )|| ISPICKVAL(Financials__c ,&apos;&apos;), &apos;&apos;, &apos;Yes&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Send Admission Letter</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Send_Admission_Letter_No_DAte_Time__c.field-meta.xml
<CustomField>
    <fullName>Send_Admission_Letter_No_DAte_Time__c</fullName>
    <label>Send Admission Letter No DAte/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BatchToAssignNOOfferLeeterLead.cls
public without sharing class BatchToAssignNOOfferLeeterLead implements Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext BC){
        string newFlowLeadRT = Constant.IdLeadNewFlowRT;
        DateTime tenNovDate = DateTime.newInstance(2022, 11, 09, 0, 0, 0);
        
        String query = 'select id,ownerId from Lead where recordtypeid =: newFlowLeadRT AND Offer_Status__c = \'No\' and  Send_Admission_Letter_No_DAte_Time__c >:tenNovDate';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Lead> leadList){
        if(!leadList.isEmpty()){
            CounsellorsAssignmentModule.counsellorAssignmentLogic(leadList);
        }
    }
    
    public void finish(Database.BatchableContext BC){
    }
    
}