force-app/main/default/objects/Lead/fields/SM_Audit_Score__c.field-meta.xml
<CustomField>
    <fullName>SM_Audit_Score__c</fullName>
    <label>SM Audit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/SM_Call_Audit_Form__c.object-meta.xml
<CustomObject>
    <label>SM Call Audit Form</label>
    <nameField>
        <displayFormat>SM Audit Form -{0000000}</displayFormat>
        <label>SM Call Audit Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SM Call Audit Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Final_Total_Score__c.field-meta.xml
<CustomField>
    <fullName>Final_Total_Score__c</fullName>
    <formula>( (Closure_Score__c  * 30)  + ( Need_Mapping_Score__c  * 15) + ( Opening_Score__c  * 10) + ( Probing_Score__c  * 25) + ( Referral_Score__c  * 10) + ( Subjective_Score__c  * 10))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Total Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>SM Call Audit Forms</relationshipLabel>
    <relationshipName>SM_Call_Audit_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SMAuditFormTriggerHandler.cls
public without sharing class SMAuditFormTriggerHandler {
    
    public static void updateLead(List<SM_Call_Audit_Form__c> SMAUditFormList){
        
        Set<Id> LeadIdList = new Set<Id>();
        Map<String, SM_Call_Audit_Form__c> MapOfLeadIdWithSMAUDitRec = new Map<String, SM_Call_Audit_Form__c>(); 
        list<Lead> LeadListTobeUpdated = new list<Lead>();
        List<Lead> FinalleadlistTobeUpdated = new List<Lead>();
        
        if(!SMAUditFormList.isEmpty()){
            for(SM_Call_Audit_Form__c SMAudit : SMAUditFormList){
                LeadIdList.add(SMAudit.Lead__c);
                MapOfLeadIdWithSMAUDitRec.put(SMAudit.Lead__c, SMAudit);
            }
        }
        if(!LeadIdList.isEmpty()){
            LeadListTobeUpdated = [Select id, SM_Audit_Score__c From Lead Where Id In: LeadIdList];
        }
        if(!LeadListTobeUpdated.isEmpty()){
            for(Lead ld : LeadListTobeUpdated){
                if(MapOfLeadIdWithSMAUDitRec.containsKey(ld.Id)){
                    ld.SM_Audit_Score__c = MapOfLeadIdWithSMAUDitRec.get(ld.Id).Final_Total_Score__c;
                    FinalleadlistTobeUpdated.add(ld);
                }
            }
        }
        if(!FinalleadlistTobeUpdated.isEmpty()){
            update FinalleadlistTobeUpdated;
        }
    }

}