force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Relevel_Interview_Id__c.field-meta.xml
<CustomField>
    <fullName>Relevel_Interview_Id__c</fullName>
    <label>Relevel Interview Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Interviewer Not Found</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Interviewer Missed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
                <isActive>false</isActive>
                <label>Disqualified</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <isActive>false</isActive>
                <label>Qualified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relevel_BackEnd_API__mdt/Relevel_BackEnd_API__mdt.object-meta.xml
<CustomObject>
    <label>Relevel BackEnd API</label>
    <pluralLabel>Relevel BackEnd API</pluralLabel>
</CustomObject>

force-app/main/default/objects/Relevel_BackEnd_API__mdt/fields/Accept__c.field-meta.xml
<CustomField>
    <fullName>Accept__c</fullName>
    <label>Accept</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relevel_BackEnd_API__mdt/fields/Auth_Header__c.field-meta.xml
<CustomField>
    <fullName>Auth_Header__c</fullName>
    <label>Auth Header</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relevel_BackEnd_API__mdt/fields/Auth_Key__c.field-meta.xml
<CustomField>
    <fullName>Auth_Key__c</fullName>
    <label>Auth Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Callout_Interview_Response.cls
public Without Sharing class Callout_Interview_Response {
    

    @future(callout=true)
    public static void sendInterviewStatusUpdate(Set<String> interviewIdSet){
        system.debug('interviewIdSet::'+interviewIdSet);
        Relevel_BackEnd_API__mdt backendAuthDet = [select id,Auth_Header__c,Auth_Key__c,End_Point_URL__c,Method__c,Content_Type__c,Accept__c from Relevel_BackEnd_API__mdt limit 1];
        List<Interview__c> interviewList = [select id,Relevel_Interview_Id__c,Status__c from Interview__c where id in: interviewIdSet];
        system.debug('interviewList::'+interviewList);
        if(!interviewList.isEmpty()){
            for(Interview__c intDet : interviewList){
                String jsonReq = generateJSON(intDet);
                HttpRequest req = new HttpRequest();
                req.setEndpoint(backendAuthDet.End_Point_URL__c);
                req.setMethod(backendAuthDet.Method__c);
                req.setHeader('Content-Type',backendAuthDet.Content_Type__c);
                req.setHeader('Accept',backendAuthDet.Accept__c);
                req.setHeader('salesforce-auth-token', backendAuthDet.Auth_Key__c);
                req.setBody(jsonReq);
        
                Http http = new Http();
                HTTPResponse res = http.send(req);
                system.debug('res.getBody()::'+res.getBody());
            }
        }
        
        
    }


    public static String generateJSON(Interview__c interviewDet){
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('relevel_interview_id',interviewDet.Relevel_Interview_Id__c);
        gen.writeStringField('status', interviewDet.Status__c);
        gen.writeEndObject();

        return gen.getAsString();
    }
}