force-app/main/default/objects/Admission_Officer_Tracking__c/Admission_Officer_Tracking__c.object-meta.xml
<CustomObject>
    <label>Admission Officer Tracking</label>
    <nameField>
        <displayFormat>AOT -{0000000}</displayFormat>
        <label>Admission Officer Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admission Officer Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Admission_Officer_Tracking__c/fields/AO_Available__c.field-meta.xml
<CustomField>
    <fullName>AO_Available__c</fullName>
    <label>AO Available</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Admission_Officer_Tracking__c/fields/AO_On_Break__c.field-meta.xml
<CustomField>
    <fullName>AO_On_Break__c</fullName>
    <label>AO On Break</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Admission_Officer_Tracking__c/fields/AO_On_Meeting__c.field-meta.xml
<CustomField>
    <fullName>AO_On_Meeting__c</fullName>
    <label>AO On Meeting</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Admission_Officer_Tracking__c/fields/AO_s_Checked_In__c.field-meta.xml
<CustomField>
    <fullName>AO_s_Checked_In__c</fullName>
    <label>AO&apos;s Checked-In</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Admission_Officer_Tracking__c/fields/Interview__c.field-meta.xml
<CustomField>
    <fullName>Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipLabel>Admission Officer Tracking</relationshipLabel>
    <relationshipName>Admission_Officer_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Admission_Officer_Tracking__c/fields/Interview_Id__c.field-meta.xml
<CustomField>
    <fullName>Interview_Id__c</fullName>
    <label>Interview Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Admission_Officer_Tracking__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Admission Officer Tracking</relationshipLabel>
    <relationshipName>Admission_Officer_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Admission_Officer_Tracking__c/fields/Not_Available_AO__c.field-meta.xml
<CustomField>
    <fullName>Not_Available_AO__c</fullName>
    <label>Not Available AO</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Admission_Officer_Tracking__c/fields/Total_AO_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_AO_Number__c</fullName>
    <label>Total AO Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/AO_Availability__c.object-meta.xml
<CustomObject>
    <label>AO Availability</label>
    <nameField>
        <displayFormat>AOA - {000}</displayFormat>
        <label>AO Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AO Availabilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Availability__c/fields/Audit_Officer__c.field-meta.xml
<CustomField>
    <fullName>Audit_Officer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Audit Officer</label>
    <referenceTo>Audit_Officer__c</referenceTo>
    <relationshipLabel>AO Availabilities</relationshipLabel>
    <relationshipName>AO_Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AO_Availability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>In Meeting</fullName>
            </value>
            <value>
                <fullName>On Break</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Officer__c/Audit_Officer__c.object-meta.xml
<CustomObject>
    <label>Admission Officer</label>
    <nameField>
        <displayFormat>AO-{000}</displayFormat>
        <label>Audit Officer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admission Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Officer__c/fields/AO__c.field-meta.xml
<CustomField>
    <fullName>AO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AO</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Audit_Officers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Interviewer Not Found</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Interviewer Missed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
                <isActive>false</isActive>
                <label>Disqualified</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <isActive>false</isActive>
                <label>Qualified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Utility.cls
public class Utility {

    public Static string getAoDetails(String leadId,String interviewId){
        try{
            /*system.debug('Admission officer ');
            system.debug('leadId-->'+leadId);
            system.debug('interviewId-->'+interviewId);
*/
            List<AO_Availability__c> AOAvailableList = new List<AO_Availability__c>();
            List<Interview__c> getInterviewList = new  List<Interview__c>();
            List<Audit_Officer__c> auditOfficerList = new List<Audit_Officer__c>();
            List<Admission_Officer_Tracking__c> AOTList = new List<Admission_Officer_Tracking__c>();
            Set<Id> InterviewIdSet = new Set<Id>();
            set<Id> AOOfficerIds = new set<Id>();
            Set<Id> leadIdSet = new Set<Id>();
            Integer AoAvailable =0;
            Integer AOOnBreak =0;
            Integer AOOnMeeting = 0;
            Integer NotAvailableAO = 0;
            Integer TotalAONumber = 0;
            
            AOAvailableList = [SELECT Id,Name,Status__c FROM AO_Availability__c WHERE CreatedDate =TODAY];
            auditOfficerList = [Select Id,AO__c From Audit_Officer__c];
            if(!auditOfficerList.isEmpty()){
                for(Audit_Officer__c AO_Rec: auditOfficerList){
                    AOOfficerIds.add(AO_Rec.AO__c);
                }
            }
            if(!AOAvailableList.isEmpty()){
                for(AO_Availability__c av: AOAvailableList){
                    if(av.Status__c =='Available'){
                        AoAvailable = AoAvailable +1;
                    }else if(av.Status__c == 'On Break'){
                        AOOnBreak = AOOnBreak +1;
                    }else if(av.Status__c == 'In Meeting'){
                        AOOnMeeting = AOOnMeeting + 1;
                    }else if(av.Status__c == 'Not Available'){
                        NotAvailableAO = NotAvailableAO + 1;
                    }
                }
                TotalAONumber = AOAvailableList.size();
            }
            
         /*   System.debug('AoAvailable Today :::'+AoAvailable);
            System.debug('AOOnBreak Today :::'+AOOnBreak);
            System.debug('AOOnMeeting Today :::'+AOOnMeeting);
            System.debug('NotAvailableAO Today :::'+NotAvailableAO);
            System.debug('TotalAONumber Today :::'+TotalAONumber);
            */
            //getInterviewList = [SELECT Id,Lead__c FROM Interview__c WHERE Id=:interviewId AND Lead__c=:leadId];
            
            Admission_Officer_Tracking__c AOT = new Admission_Officer_Tracking__c();
            AOT.AO_Available__c = Double.valueOf(AoAvailable);
            AOT.AO_On_Break__c = Double.valueOf(AOOnBreak);
            AOT.AO_On_Meeting__c = Double.valueOf(AOOnMeeting);
            AOT.Not_Available_AO__c = Double.valueOf(AOOfficerIds.size()) - Double.valueOf(TotalAONumber);
            AOT.Total_AO_Number__c = Double.valueOf(AOOfficerIds.size());
            AOT.AO_s_Checked_In__c = Double.valueOf(TotalAONumber);
            AOT.Interview_Id__c = interviewId;
            AOT.Lead__c = leadId;
            insert AOT;
            return 'success';
        }Catch(Exception e){
            System.debug('The Error ::'+e.getMessage() +' AND Error Line No :'+e.getLineNumber());   
            return 'error';
        }
    }
}