force-app/main/default/objects/BDA_KPI_Details__c/BDA_KPI_Details__c.object-meta.xml
<CustomObject>
    <label>BDA KPI Details</label>
    <nameField>
        <displayFormat>BKD-{000000}</displayFormat>
        <label>BDA KPI Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDA KPI Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BDA_KPI_Details__c/fields/AOV__c.field-meta.xml
<CustomField>
    <fullName>AOV__c</fullName>
    <label>AOV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BDA_KPI_Details__c/fields/ATT_Day__c.field-meta.xml
<CustomField>
    <fullName>ATT_Day__c</fullName>
    <label>ATT/Day</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BDA_KPI_Details__c/fields/Called_Leads__c.field-meta.xml
<CustomField>
    <fullName>Called_Leads__c</fullName>
    <label>Called Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BDA_KPI_Details__c/fields/Connect_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Connect_Conversion__c</fullName>
    <label>Connect Conversion</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BDA_KPI_Details__c/fields/Connected_Calls__c.field-meta.xml
<CustomField>
    <fullName>Connected_Calls__c</fullName>
    <label>Connected Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BDA_KPI_Details__c/fields/Connected_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Connected_Percentage__c</fullName>
    <label>Connected Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BDA_KPI_Details__c/fields/Lead_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Lead_Conversion__c</fullName>
    <label>Lead Conversion</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BDA_KPI_Details__c/fields/New_Leads_Count__c.field-meta.xml
<CustomField>
    <fullName>New_Leads_Count__c</fullName>
    <label>New Leads Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BDA_KPI_Details__c/fields/Talktime_In_Second__c.field-meta.xml
<CustomField>
    <fullName>Talktime_In_Second__c</fullName>
    <label>Talk Time In Second</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BDA_KPI_Details__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BDA_KPI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Call_Count__c.field-meta.xml
<CustomField>
    <fullName>Call_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Connected Call Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Called_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Called_Percentage__c</fullName>
    <formula>Called_Unique__c  /  Lead_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Called Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Connected_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Connected_Percentage__c</fullName>
    <formula>Connected_Unique__c  /  Called_Unique__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Connected Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Goal_Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Goal_Interested_In__c</fullName>
    <label>Course Interested In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business-Development</fullName>
            </value>
            <value>
                <fullName>Frontend-Development</fullName>
            </value>
            <value>
                <fullName>Backend-Development</fullName>
            </value>
            <value>
                <fullName>Full-Stack-Development</fullName>
            </value>
            <value>
                <fullName>Data-Analytics</fullName>
            </value>
            <value>
                <fullName>Associate-Product-Management</fullName>
            </value>
            <value>
                <fullName>Business-Analytics</fullName>
            </value>
            <value>
                <fullName>HR-Generalist</fullName>
            </value>
            <value>
                <fullName>Digital-Marketing</fullName>
            </value>
            <value>
                <fullName>Software-Testing</fullName>
            </value>
            <value>
                <fullName>operations-associate</fullName>
                <label>Operations-Associate</label>
            </value>
            <value>
                <fullName>Graphic-Designer</fullName>
            </value>
            <value>
                <fullName>Mechanical-Engineering</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
                <default>true</default>
                <label>Unassigned</label>
            </value>
            <value>
                <fullName>Conducted</fullName>
            </value>
            <value>
                <fullName>Offer Rolled Out</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Called</fullName>
            </value>
            <value>
                <fullName>Nurturing</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Payment_details__c.field-meta.xml
<CustomField>
    <fullName>Payment_details__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Payment details</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
                <default>true</default>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BDADailyKPI.cls
public class BDADailyKPI {
    
    public static void bdsKPICalculation(){
        list<BDA_KPI_Details__c> bdaKPIDetailsList = new list<BDA_KPI_Details__c>();
        list<BDA_KPI_Details__c> bdakpilist = new list<BDA_KPI_Details__c>();
        set<string> bdakpiIdSet = new set<string>();
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = task.wk_exo__Exotel_Call_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }
        
        map<string,BDA_KPI_Details__c> mapofUseridByKPICal = new map<String,BDA_KPI_Details__c>();
        map<string,list<lead>> mapofLeadidByLeadRec = new map<string,list<lead>>();
        map<string,integer> mapofLeadidByCalledCount = new map<string,integer>();
        map<string,integer> mapofLeadidByConnectCount = new map<string,integer>();
        map<string,integer> mapofLeadidByCallDuration = new map<string,integer>();
        Map<string,string> mapofUserIdByRecId = new map<String,String>();
        
        string queueId = [SELECT Id, Type FROM Group WHERE Type = 'Queue' AND Name = 'Relevel Default Queue' limit 1].Id;
        //Lead_Assigned_Date__c
        list<lead> leadList = [select id,lead_stage__c,ownerId,Goal_Interested_In__c,Call_Count__c,Payment_details__c,Temperature__c from lead where Lead_Assigned_Date__c = today and ownerid !=: queueId limit 50000];
        //activity_date_Time
        list<task> taskList = [select id,Call_Duration__c,wk_exo__Total_Talk_Time__c,wk_exo__Exotel_Call_Type__c,whoId,wk_exo__exotel_dial_status__c from task where wk_exo__Exotel_Call_Type__c in : pickListValuesList and whoId != null AND createddate = today limit 50000];
        if(!taskList.isEmpty()){
            for(task ts : taskList){
                mapofLeadidByCalledCount.put(ts.whoId,1);
                if(ts.wk_exo__Total_Talk_Time__c != '0' && ts.wk_exo__Total_Talk_Time__c != null){
                    if(mapofLeadidByCallDuration.containsKey(ts.whoId)){
                        integer connectDuration = mapofLeadidByCallDuration.get(ts.whoId) + Integer.valueOf(ts.wk_exo__Total_Talk_Time__c);
                        mapofLeadidByCallDuration.put(ts.whoId,connectDuration);
                    }else{
                        mapofLeadidByConnectCount.put(ts.whoId,1);
                        mapofLeadidByCallDuration.put(ts.whoId,Integer.valueOf(ts.wk_exo__Total_Talk_Time__c));
                    }
                }
            }
        }
        if(!leadList.isEmpty()){
            for(lead ld : leadList){
                bdakpiIdSet.add(ld.ownerId);
                if(mapofLeadidByLeadRec.containsKey(ld.ownerId)){
                    mapofLeadidByLeadRec.get(ld.ownerId).add(ld);
                }else{
                    mapofLeadidByLeadRec.put(ld.ownerId,new list<lead>{ld}); 
                }
            }
            
            if(!bdakpiIdSet.isEmpty())
                bdakpilist = [select Id,User__c from BDA_KPI_Details__c where User__c in: bdakpiIdSet and createddate = today];
            if(!bdakpilist.isEmpty()){
                for(BDA_KPI_Details__c bdaKPI : bdakpilist){
                    mapofUserIdByRecId.put(bdaKPI.User__c,bdaKPI.Id);
                }
            }
            if(!mapofLeadidByLeadRec.isEmpty()){
                for(string ownerId : mapofLeadidByLeadRec.keySet()){
                    integer newLeadCount = 0;
                    BDA_KPI_Details__c bdaKPIDetail = new BDA_KPI_Details__c();
                    bdaKPIDetail.User__c = ownerId;
                    if(mapofLeadidByLeadRec.containsKey(ownerId))
                        if(mapofLeadidByLeadRec.get(ownerId) != null && mapofLeadidByLeadRec.get(ownerId).size() != null )
                        bdaKPIDetail.Total_Leads__c = mapofLeadidByLeadRec.get(ownerId).size();
                    for(lead ld : mapofLeadidByLeadRec.get(ownerId)){
                        if(ld.Lead_Stage__c == 'New'){
                            newLeadCount++;
                        }
                        if(bdaKPIDetail.New_Leads_Count__c == null)
                            bdaKPIDetail.New_Leads_Count__c = 0;
                        bdaKPIDetail.New_Leads_Count__c = bdaKPIDetail.New_Leads_Count__c + newLeadCount;
                        if(bdaKPIDetail.Called_Leads__c == null)
                            bdaKPIDetail.Called_Leads__c = 0;
                        if(mapofLeadidByCalledCount.get(ld.Id) != null)
                            bdaKPIDetail.Called_Leads__c = bdaKPIDetail.Called_Leads__c + mapofLeadidByCalledCount.get(ld.Id);
                        if(bdaKPIDetail.Connected_Calls__c == null)
                            bdaKPIDetail.Connected_Calls__c = 0;
                        if(mapofLeadidByConnectCount.get(ld.Id) != null)
                            bdaKPIDetail.Connected_Calls__c = bdaKPIDetail.Connected_Calls__c + mapofLeadidByConnectCount.get(ld.Id);
                        if(bdaKPIDetail.Called_Leads__c != 0 && bdaKPIDetail.Called_Leads__c != null)
                            bdaKPIDetail.Called_Percentage__c =  bdaKPIDetail.Called_Leads__c * 100/bdaKPIDetail.Total_Leads__c;
                        if(bdaKPIDetail.Connected_Calls__c != 0 && bdaKPIDetail.Connected_Calls__c != null){
                            bdaKPIDetail.Connected_Percentage__c = bdaKPIDetail.Connected_Calls__c * 100 / bdaKPIDetail.Called_Leads__c;// Changed bdaKPIDetail.Total_Leads__c => bdaKPIDetail.Called_Leads__c
                        }
                        if(ld.Payment_details__c != null && ld.Payment_details__c > 0){
                            if(bdaKPIDetail.Revenue__c == null)
                                bdaKPIDetail.Revenue__c = 0;
                            bdaKPIDetail.Revenue__c = bdaKPIDetail.Revenue__c + ld.Payment_details__c;
                            if(bdaKPIDetail.Order__c == null)
                                bdaKPIDetail.Order__c = 0;
                            bdaKPIDetail.Order__c = bdaKPIDetail.Order__c + 1;
                            if(bdaKPIDetail.Called_Leads__c != 0)
                                bdaKPIDetail.Called_Conversion__c = bdaKPIDetail.Order__c * 100 / bdaKPIDetail.Called_Leads__c;
                            if(bdaKPIDetail.Connected_Calls__c != 0)
                                bdaKPIDetail.Connect_Conversion__c = bdaKPIDetail.Order__c * 100 / bdaKPIDetail.Connected_Calls__c;
                            if(bdaKPIDetail.Order__c != 0)
                                bdaKPIDetail.Lead_Conversion__c = bdaKPIDetail.Total_Leads__c * 100 /bdaKPIDetail.Order__c;
                            if(bdaKPIDetail.Order__c != 0 && bdaKPIDetail.Revenue__c  != 0){
                                bdaKPIDetail.AOV__c = bdaKPIDetail.Revenue__c / bdaKPIDetail.Order__c;
                            }
                        }
                        if(mapofLeadidByCallDuration.get(ld.Id) != null){
                            if(bdaKPIDetail.Talktime_In_Second__c == null)
                                bdaKPIDetail.Talktime_In_Second__c = 0;
                            bdaKPIDetail.Talktime_In_Second__c = mapofLeadidByCallDuration.get(ld.Id)*1000;
                            bdaKPIDetail.ATT_Day__c = DateTime.valueOf(mapofLeadidByCallDuration.get(ld.Id)*1000).formatGMT('HH:mm:ss');
                        }
                        
                        if(mapofUserIdByRecId.containsKey(ownerId)){
                            bdaKPIDetail.Id = mapofUserIdByRecId.get(ownerId);
                        }
                    }
                    bdaKPIDetailsList.add(bdaKPIDetail);
                }
                upsert bdaKPIDetailsList;
            }
        }
        
    }
    
}