force-app/main/default/objects/SM_Call_Audit_Form__c/SM_Call_Audit_Form__c.object-meta.xml
<CustomObject>
    <label>SM Call Audit Form</label>
    <nameField>
        <displayFormat>SM Audit Form -{0000000}</displayFormat>
        <label>SM Call Audit Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SM Call Audit Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_Area_of_Improvement__c.field-meta.xml
<CustomField>
    <fullName>Closure_Area_of_Improvement__c</fullName>
    <label>Closure Area of Improvement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_Audited_by__c.field-meta.xml
<CustomField>
    <fullName>Closure_Audited_by__c</fullName>
    <label>Closure Audited by</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_Call_Number__c.field-meta.xml
<CustomField>
    <fullName>Closure_Call_Number__c</fullName>
    <label>Closure Call Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Closure_End_Date__c</fullName>
    <label>Closure End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_End_Time_in_min__c.field-meta.xml
<CustomField>
    <fullName>Closure_End_Time_in_min__c</fullName>
    <label>Closure End Time (in min)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_End_Time_in_sec__c.field-meta.xml
<CustomField>
    <fullName>Closure_End_Time_in_sec__c</fullName>
    <label>Closure End Time (in sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_Positive_Points__c.field-meta.xml
<CustomField>
    <fullName>Closure_Positive_Points__c</fullName>
    <label>Closure Positive Points</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_Score__c.field-meta.xml
<CustomField>
    <fullName>Closure_Score__c</fullName>
    <label>Closure Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Closure_Start_Date__c</fullName>
    <label>Closure Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_Start_Time_in_min__c.field-meta.xml
<CustomField>
    <fullName>Closure_Start_Time_in_min__c</fullName>
    <label>Closure Start Time (in min)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_Start_Time_in_sec__c.field-meta.xml
<CustomField>
    <fullName>Closure_Start_Time_in_sec__c</fullName>
    <label>Closure Start Time (in sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Customer_profile_details__c.field-meta.xml
<CustomField>
    <fullName>Customer_profile_details__c</fullName>
    <label>Customer profile details</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Incorrect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent__c</fullName>
    <label>Email Sent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Incorrect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Final_Total_Score__c.field-meta.xml
<CustomField>
    <fullName>Final_Total_Score__c</fullName>
    <formula>( (Closure_Score__c  * 30)  + ( Need_Mapping_Score__c  * 15) + ( Opening_Score__c  * 10) + ( Probing_Score__c  * 25) + ( Referral_Score__c  * 10) + ( Subjective_Score__c  * 10))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Total Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Follow_up_adherenece__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_adherenece__c</fullName>
    <label>Follow up adherenece</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Incorrect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Follow_up_created__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_created__c</fullName>
    <label>Follow up created</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Incorrect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>SM Call Audit Forms</relationshipLabel>
    <relationshipName>SM_Call_Audit_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Lead_Stages__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stages__c</fullName>
    <label>Lead Stages</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Incorrect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Need_Mapping_Area_of_Improvement__c.field-meta.xml
<CustomField>
    <fullName>Need_Mapping_Area_of_Improvement__c</fullName>
    <label>Need Mapping Area of Improvement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Need_Mapping_Audited_By__c.field-meta.xml
<CustomField>
    <fullName>Need_Mapping_Audited_By__c</fullName>
    <label>Need Mapping Audited By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Need_Mapping_Call_Number__c.field-meta.xml
<CustomField>
    <fullName>Need_Mapping_Call_Number__c</fullName>
    <label>Need Mapping Call Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Need_Mapping_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Need_Mapping_End_Date__c</fullName>
    <label>Need Mapping End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Need_Mapping_End_Time_in_min__c.field-meta.xml
<CustomField>
    <fullName>Need_Mapping_End_Time_in_min__c</fullName>
    <label>Need Mapping End Time (in min)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Need_Mapping_End_Time_in_sec__c.field-meta.xml
<CustomField>
    <fullName>Need_Mapping_End_Time_in_sec__c</fullName>
    <label>Need Mapping End Time (in sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Need_Mapping_Positive_points__c.field-meta.xml
<CustomField>
    <fullName>Need_Mapping_Positive_points__c</fullName>
    <label>Need Mapping Positive points</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Need_Mapping_Score__c.field-meta.xml
<CustomField>
    <fullName>Need_Mapping_Score__c</fullName>
    <label>Need Mapping Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Need_Mapping_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Need_Mapping_Start_Date__c</fullName>
    <label>Need Mapping Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Need_mapping_Start_Time_in_min__c.field-meta.xml
<CustomField>
    <fullName>Need_mapping_Start_Time_in_min__c</fullName>
    <label>Need mapping Start Time (in min)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Need_mapping_Start_Time_in_sec__c.field-meta.xml
<CustomField>
    <fullName>Need_mapping_Start_Time_in_sec__c</fullName>
    <label>Need mapping Start Time(in sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Incorrect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Opening_Area_Of_Improvement__c.field-meta.xml
<CustomField>
    <fullName>Opening_Area_Of_Improvement__c</fullName>
    <label>Opening Area Of Improvement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Opening_Audited_By__c.field-meta.xml
<CustomField>
    <fullName>Opening_Audited_By__c</fullName>
    <label>Opening Audited By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Opening_Call_Number__c.field-meta.xml
<CustomField>
    <fullName>Opening_Call_Number__c</fullName>
    <label>Opening Call Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Opening_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Opening_End_Date__c</fullName>
    <label>Opening End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Opening_End_Time_in_min__c.field-meta.xml
<CustomField>
    <fullName>Opening_End_Time_in_min__c</fullName>
    <label>Opening End Time (in min)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Opening_End_Time_in_sec__c.field-meta.xml
<CustomField>
    <fullName>Opening_End_Time_in_sec__c</fullName>
    <label>Opening End Time (in sec)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Opening_Positive_Points__c.field-meta.xml
<CustomField>
    <fullName>Opening_Positive_Points__c</fullName>
    <label>Opening Positive Points</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Opening_Score__c.field-meta.xml
<CustomField>
    <fullName>Opening_Score__c</fullName>
    <label>Opening Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Opening_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Opening_Start_Date__c</fullName>
    <label>Opening Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Opening_Start_Time_in_min__c.field-meta.xml
<CustomField>
    <fullName>Opening_Start_Time_in_min__c</fullName>
    <label>Opening Start Time (in min)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Opening_Start_Time_in_sec__c.field-meta.xml
<CustomField>
    <fullName>Opening_Start_Time_in_sec__c</fullName>
    <label>Opening Start Time (in sec)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Probing_Area_of_Improvement__c.field-meta.xml
<CustomField>
    <fullName>Probing_Area_of_Improvement__c</fullName>
    <label>Probing Area of Improvement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Probing_Audited_by__c.field-meta.xml
<CustomField>
    <fullName>Probing_Audited_by__c</fullName>
    <label>Probing Audited by</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Probing_Call_Number__c.field-meta.xml
<CustomField>
    <fullName>Probing_Call_Number__c</fullName>
    <label>Probing Call Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Probing_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Probing_End_Date__c</fullName>
    <label>Probing End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Probing_End_Time_in_min__c.field-meta.xml
<CustomField>
    <fullName>Probing_End_Time_in_min__c</fullName>
    <label>Probing End Time (in min)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SMAuditFormController.cls
public without sharing class SMAuditFormController {
    
    @AuraEnabled
    Public Static SMAUditWrapper getRecordOnDoint(String recId){
        system.debug('recId :: ' + recId);
        
        SMAUditWrapper AuditWrap = new SMAUditWrapper();
        Map<String,List<String>> pickValByField = new Map<String,List<String>>();
        try{
            
            List<Task> TaskCountOfDialledCall = [SELECT Id FROM Task where whoId =: recId AND wk_exo__call_recording_url__c != null];
            List<SM_Call_Audit_Form__c> SMAudForm = [SELECT Closure_Area_of_Improvement__c,Closure_Audited_by__c,Closure_Call_Number__c,Closure_End_Date__c,
															Closure_End_Time_in_min__c,Closure_End_Time_in_sec__c,Closure_Positive_Points__c,Closure_Score__c,Closure_Start_Date__c,
                                                     		Closure_Start_Time_in_min__c,Closure_Start_Time_in_sec__c,CreatedById,CreatedDate,Customer_profile_details__c,
                                                     		Email_Sent__c,Final_Total_Score__c,Follow_up_adherenece__c,Follow_up_created__c,Id,IsDeleted,LastActivityDate,
                                                     		LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Lead_Stages__c,Lead__c,Name,Need_Mapping_Area_of_Improvement__c,
                                                     		Need_Mapping_Audited_By__c,Need_Mapping_Call_Number__c,Need_Mapping_End_Date__c,Need_Mapping_End_Time_in_min__c,Need_Mapping_End_Time_in_sec__c,
                                                     		Need_Mapping_Positive_points__c,Need_Mapping_Score__c,Need_Mapping_Start_Date__c,Need_mapping_Start_Time_in_min__c,Need_mapping_Start_Time_in_sec__c,
                                                     		Notes__c,Opening_Area_Of_Improvement__c,Opening_Audited_By__c,Opening_Call_Number__c,Opening_End_Date__c,Opening_End_Time_in_min__c,
                                                     		Opening_End_Time_in_sec__c,Opening_Positive_Points__c,Opening_Score__c,Opening_Start_Date__c,Opening_Start_Time_in_min__c,Opening_Start_Time_in_sec__c,OwnerId,
                                                     		Probing_Area_of_Improvement__c,Probing_Audited_by__c,Probing_Call_Number__c,Probing_End_Date__c,Probing_End_Time_in_min__c,Probing_End_Time_in_sec__c,
                                                     		Probing_Positive_Points__c,Probing_Score__c,Probing_Start_Date__c,Probing_Start_Time_in_min__c,Probing_Start_Time_in_sec__c,Referral_Area_of_Improvement__c,
                                                     		Referral_Audited_by__c,Referral_Call_Number__c,Referral_End_Date__c,Referral_End_Time_in_min__c,Referral_End_Time_in_sec__c,Referral_Positive_Points__c,
                                                     		Referral_Score__c,Referral_Start_Date__c,Referral_Start_Time_in_min__c,Referral_Start_Time_in_sec__c,Subjective_Area_of_Improvement__c,Subjective_Audited_by__c,
                                                     		Subjective_Call_Number__c,Subjective_End_Date__c,Subjective_End_Time_in_min__c,Subjective_End_Time_in_sec__c,Subjective_Positive_Points__c,Subjective_Score__c,
                                                     		Subjective_Start_Date__c,Subjective_Start_Time_in_min__c,Subjective_Start_Time_in_sec__c,SystemModstamp,Temperature_Type__c,Temperature__c 
                                                     		FROM SM_Call_Audit_Form__c Where Lead__c =:recId];
            
            pickValByField.put('Customer_profile_details__c',LeadAuditForm.getPicklistValues('SM_Call_Audit_Form__c','Customer_profile_details__c'));
            pickValByField.put('Email_Sent__c',LeadAuditForm.getPicklistValues('SM_Call_Audit_Form__c','Email_Sent__c'));
            pickValByField.put('Follow_up_adherenece__c',LeadAuditForm.getPicklistValues('SM_Call_Audit_Form__c','Follow_up_adherenece__c'));
            pickValByField.put('Follow_up_created__c',LeadAuditForm.getPicklistValues('SM_Call_Audit_Form__c','Follow_up_created__c'));
            pickValByField.put('Lead_Stages__c',LeadAuditForm.getPicklistValues('SM_Call_Audit_Form__c','Lead_Stages__c'));
            pickValByField.put('Notes__c',LeadAuditForm.getPicklistValues('SM_Call_Audit_Form__c','Notes__c'));
            pickValByField.put('Temperature__c',LeadAuditForm.getPicklistValues('SM_Call_Audit_Form__c','Temperature__c'));
            pickValByField.put('Temperature_Type__c',LeadAuditForm.getPicklistValues('SM_Call_Audit_Form__c','Temperature_Type__c'));
            
            if(!TaskCountOfDialledCall.isEmpty()){
                AuditWrap.tasklist = TaskCountOfDialledCall;
                AuditWrap.taskSize = TaskCountOfDialledCall.size();
            }
            else if(TaskCountOfDialledCall.isEmpty()){
                AuditWrap.tasklist = null;
                AuditWrap.taskSize = TaskCountOfDialledCall.size();
            }
            if(SMAudForm.size() >0){
                AuditWrap.isAuditFormFilled = true;
                AuditWrap.SMCallAuditRec = SMAudForm[0];
            }
            else{
                AuditWrap.isAuditFormFilled = false;
            }
            
            if(!pickValByField.isEmpty()){
                AuditWrap.MapofPickListbyValue = pickValByField;
            }
            system.debug('AuditWrap :: ' + AuditWrap);
            return AuditWrap;
        }
        catch(Exception e){
            System.debug('The following exception has occurred:: ' + e.getMessage() + ' @@@@@ at Line Number :: ' + e.getLineNumber());
        } 
        return AuditWrap;
    }
    
    @AuraEnabled 
    Public static string SaveSMAuditFormRec(SM_Call_Audit_Form__c SMAuditRecord, String recId){
        if(SMAuditRecord !=null && recId != null){
            SMAuditRecord.Lead__c = recId;
        	insert SMAuditRecord;
        }
        
        return 'success';
    }
    
    public class SMAUditWrapper{
    @auraEnabled
    public List<Task> tasklist{get; set;}
    @auraEnabled
    public Boolean isAuditFormFilled  {get; set;}
    @AuraEnabled
    public Map<String,List<String>> MapofPickListbyValue{get;set;}
    @AuraEnabled
    public SM_Call_Audit_Form__c SMCallAuditRec {get;set;}
    @AuraEnabled
    public decimal taskSize {get;set;}
    
    }
}