force-app/main/default/objects/SM_Call_Audit_Form__c/SM_Call_Audit_Form__c.object-meta.xml
<CustomObject>
    <label>SM Call Audit Form</label>
    <nameField>
        <displayFormat>SM Audit Form -{0000000}</displayFormat>
        <label>SM Call Audit Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SM Call Audit Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_Area_of_Improvement__c.field-meta.xml
<CustomField>
    <fullName>Closure_Area_of_Improvement__c</fullName>
    <label>Closure Area of Improvement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_Call_Number__c.field-meta.xml
<CustomField>
    <fullName>Closure_Call_Number__c</fullName>
    <label>Closure Call Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Call_Audit_Form__c/fields/Closure_Score__c.field-meta.xml
<CustomField>
    <fullName>Closure_Score__c</fullName>
    <label>Closure Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SMAuditFormTriggerHandlerTest.cls
@isTest
public class SMAuditFormTriggerHandlerTest {
    
    @isTest static void SMAuditFormTest(){
        SM_Call_Audit_Form__c SMAud = new SM_Call_Audit_Form__c();
        SMAud.Closure_Score__c = 6;
        SMAud.Closure_Area_of_Improvement__c = 'Need improvement';
        SMAud.Closure_Call_Number__c = 'Call 1';
        
        Test.startTest();
        insert SMAud; 
        Test.stopTest();
    }

}