force-app/main/default/objects/Activity/fields/Activity_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Activity_Date_Time__c</fullName>
    <label>Activity Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sign up</fullName>
            </value>
            <value>
                <fullName>Test Registered</fullName>
            </value>
            <value>
                <fullName>Test Taken</fullName>
            </value>
            <value>
                <fullName>Talk to Us</fullName>
            </value>
            <value>
                <fullName>Payment Failed</fullName>
            </value>
            <value>
                <fullName>Payment Successful</fullName>
            </value>
            <value>
                <fullName>No Cost EMI Financepeer</fullName>
            </value>
            <value>
                <fullName>Lead from Support Chat</fullName>
            </value>
            <value>
                <fullName>Abandoned Cart</fullName>
            </value>
            <value>
                <fullName>Brochure Download</fullName>
            </value>
            <value>
                <fullName>Course Selection</fullName>
            </value>
            <value>
                <fullName>Course Page - Career Impact PDF Download</fullName>
            </value>
            <value>
                <fullName>Pay Now Clicked</fullName>
            </value>
            <value>
                <fullName>Stage Changed</fullName>
            </value>
            <value>
                <fullName>Email Interaction</fullName>
            </value>
            <value>
                <fullName>IVR Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity/fields/Cohort_Id__c.field-meta.xml
<CustomField>
    <fullName>Cohort_Id__c</fullName>
    <label>Cohort Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Cohort_Name__c.field-meta.xml
<CustomField>
    <fullName>Cohort_Name__c</fullName>
    <label>Cohort Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Course_Id__c.field-meta.xml
<CustomField>
    <fullName>Course_Id__c</fullName>
    <label>Course Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Course_Slug__c.field-meta.xml
<CustomField>
    <fullName>Course_Slug__c</fullName>
    <label>Course Slug</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Date_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Payment__c</fullName>
    <label>Date of Payment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Exam_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Booked_Date__c</fullName>
    <label>Exam Booked Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Exam_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Date__c</fullName>
    <label>Exam Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Exam_Name__c.field-meta.xml
<CustomField>
    <fullName>Exam_Name__c</fullName>
    <label>Exam Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Exam_Score__c.field-meta.xml
<CustomField>
    <fullName>Exam_Score__c</fullName>
    <label>Exam Score</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Exam_Slug__c.field-meta.xml
<CustomField>
    <fullName>Exam_Slug__c</fullName>
    <label>Exam Slug</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Is_Qualified_in_Exam__c.field-meta.xml
<CustomField>
    <fullName>Is_Qualified_in_Exam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Qualified in Exam</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Payment_Failure_Reason__c.field-meta.xml
<CustomField>
    <fullName>Payment_Failure_Reason__c</fullName>
    <label>Payment Failure Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Payment_type__c.field-meta.xml
<CustomField>
    <fullName>Payment_type__c</fullName>
    <label>Payment type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Redirect_Url__c.field-meta.xml
<CustomField>
    <fullName>Redirect_Url__c</fullName>
    <label>Redirect Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Search_By_Value__c.field-meta.xml
<CustomField>
    <fullName>Search_By_Value__c</fullName>
    <label>Search By Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Skill_Based_Exam_Score__c.field-meta.xml
<CustomField>
    <fullName>Skill_Based_Exam_Score__c</fullName>
    <label>Skill Based Exam Score</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Student_Availability__c.field-meta.xml
<CustomField>
    <fullName>Student_Availability__c</fullName>
    <label>Student Availability</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Tier_Info__c.field-meta.xml
<CustomField>
    <fullName>Tier_Info__c</fullName>
    <label>Tier Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <label>Course Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Analytics Course</fullName>
            </value>
            <value>
                <fullName>Operations Management Course</fullName>
            </value>
            <value>
                <fullName>Digital Marketing Course</fullName>
            </value>
            <value>
                <fullName>Business Development Course</fullName>
            </value>
            <value>
                <fullName>Human Resources Generalist Course</fullName>
            </value>
            <value>
                <fullName>Product Management Course</fullName>
            </value>
            <value>
                <fullName>Data Science Course</fullName>
            </value>
            <value>
                <fullName>Backend Development Course</fullName>
            </value>
            <value>
                <fullName>Fullstack Development Course</fullName>
            </value>
            <value>
                <fullName>Software Testing Course</fullName>
            </value>
            <value>
                <fullName>Frontend Development Course</fullName>
            </value>
            <value>
                <fullName>Business-Development-Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Learner_Uid__c.field-meta.xml
<CustomField>
    <fullName>Learner_Uid__c</fullName>
    <defaultValue>&quot;CTI&quot;</defaultValue>
    <label>Learner Uid</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Tier_Info__c.field-meta.xml
<CustomField>
    <fullName>Tier_Info__c</fullName>
    <label>Tier Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Webservice_CreateActivity.cls
@RestResource(urlMapping='/activity_creation_event/*')
global class Webservice_CreateActivity {
    global static list<object> ob = new list<object>();
    @HttpPost
    global static ActivityModel.ReponseWrapper createActivityAgainstLead(){
        
        system.debug('RestContext.request.requestBody.tostring()::'+RestContext.request.requestBody.tostring());
        
        map<string,string> mapofUseridByLeadid = new map<string,string>();
        Map<String,String> leadOwnerIdByLearnerUID = new Map<String,String>();
        map<string,ActivityModel.ActivityDetails> mapofUseridByUseractRec = new map<string,ActivityModel.ActivityDetails>();
        list<task> activityListTobeInsert = new list<task>();
        set<string> userUniqueId = new set<string>();
        list<lead> leadList = new list<lead>();
        List<Object> activityWithoutLeadRec = new list<object>();
        ActivityModel.ReponseWrapper responseData = new ActivityModel.ReponseWrapper();
        String JSONInput = RestContext.request.requestBody.tostring();
        List<Object> activityRequestList = (List<Object>) JSON.deserializeUntyped(JSONInput);
        list<ActivityModel.failuredata> failureList = new list<ActivityModel.failuredata>();
        try{
             if(!activityRequestList.isEmpty()){
                            for(object obj : activityRequestList){
                                map<string,object> temp = (map<string,object>)obj;
                                if(temp.get('search_by_value') != null){
                                    userUniqueId.add(String.valueOf(temp.get('search_by_value')));  
                                }
                            }
                            leadList = [select id,Learner_Uid__c,OwnerId,Owner_Email__c  from lead where Learner_Uid__c in: userUniqueId];
                            for(lead ld : leadList){
                                mapofUseridByLeadid.put(ld.Learner_Uid__c,ld.Id);
                                if(ld.Owner_Email__c != null){
                                    leadOwnerIdByLearnerUID.put(ld.Learner_Uid__c,ld.OwnerId);
                                }
                            }
                            for(object obj : activityRequestList){
                                map<string,object> temp = (map<string,object>)obj;
                                System.debug(mapofUseridByLeadid.get(String.valueOf(temp.get('search_by_value'))));
                                System.debug(String.valueOf(temp.get('search_by_value')));
                                if(mapofUseridByLeadid.get(String.valueOf(temp.get('search_by_value'))) == null){
                                    activityWithoutLeadRec.add(obj);
                                    continue;
                                }
                                /*if(mapofUseridByLeadid.get(String.valueOf(temp.get('search_by_value')) == null){
                                    /*do remove operation
                                }*/
                                task ts = new task();
                                if(temp.get('activity_type') != null)
                                    ts.Activity_Type__c = String.valueOf(temp.get('activity_type'));
                                if(temp.get('search_by_value') != null)
                                    ts.Search_By_Value__c = String.valueOf(temp.get('search_by_value'));
                                if(mapofUseridByLeadid.get(ts.Search_By_Value__c) != null)
                                    ts.whoId = mapofUseridByLeadid.get(ts.Search_By_Value__c);
                                if(temp.get('activity_type') != null)
                                    ts.subject  = String.valueOf(temp.get('activity_type'));
                                if(temp.get('activity_datetime') != null)
                                    ts.Activity_date_time__C = (DateTime)JSON.deserialize('"' + String.valueOf(temp.get('activity_datetime')) + '"', DateTime.class);
                                system.debug('ts.Activity_date_time__C-->'+ts.Activity_date_time__C);
                                if(temp.get('state') != null)
                                    ts.State__c = string.valueOf(temp.get('state'));
                                if(temp.get('email') != null)
                                    ts.Email__c = String.valueOf(temp.get('email'));
                                if(temp.get('exam_name') != null)
                                    ts.Exam_Name__c = String.valueOf(temp.get('exam_name'));
                                if(temp.get('exam_slug') != null)
                                    ts.Exam_Slug__c = String.valueOf(temp.get('exam_slug'));
                                if(temp.get('exam_date') != null)
                                    ts.Exam_Date__c = (DateTime)JSON.deserialize('"' + String.valueOf(temp.get('exam_date')) + '"', DateTime.class);
                                if(temp.get('exam_booked_date') != null)
                                    ts.Exam_Booked_Date__c = (DateTime)JSON.deserialize('"' + String.valueOf(temp.get('exam_booked_date')) + '"', DateTime.class);
                                if(temp.get('exam_score') != null)
                                  ts.Exam_Score__c = String.valueOf(String.valueOf(temp.get('exam_score')));
                                if(temp.get('skill_based_exam_score') != null)
                                  ts.Skill_Based_Exam_Score__c = String.valueOf(temp.get('skill_based_exam_score'));
                                if(temp.get('is_qualified_in_exam') != null)
                                    ts.Is_Qualified_in_Exam__c = Boolean.valueOf(temp.get('is_qualified_in_exam'));
                                if(temp.get('course_name') != null)
                                    ts.Course_Name__c = String.valueOf(temp.get('course_name'));
                                if(temp.get('course_id') != null)
                                    ts.Course_Id__c = String.valueOf(temp.get('course_id'));
                                if(temp.get('Course_Slug__c') != null)
                                    ts.Course_Slug__c = String.valueOf(temp.get('Course_Slug__c'));
                                if(temp.get('student_availability') != null)
                                    ts.Student_Availability__c = (DateTime)JSON.deserialize('"' + String.valueOf(temp.get('student_availability')) + '"', DateTime.class);
                                if(temp.get('payment_failure_reason') != null)
                                    ts.Payment_Failure_Reason__c = String.valueOf(temp.get('payment_failure_reason '));
                                if(temp.get('payment_type') != null)
                                    ts.Payment_type__c = String.valueOf(temp.get('payment_type'));
                                if(temp.get('payment_amount') != null)
                                    ts.Payment_Amount__c = Decimal.valueOf(String.valueOf(temp.get('payment_amount')));
                                if(temp.get('date_of_payment') != null)
                                    ts.Date_of_Payment__c = (DateTime)JSON.deserialize('"' + String.valueOf(temp.get('date_of_payment')) + '"', DateTime.class);
                                if(temp.get('revenue') != null)
                                    ts.Revenue__c = Decimal.valueOf(String.valueOf(temp.get('revenue')));
                                if(temp.get('mobile') != null)
                                    ts.Mobile__c = String.valueOf(temp.get('mobile'));
                                if(temp.get('user_id') != null)
                                    ts.User_Id__c = String.valueOf(temp.get('user_id'));
                                if(temp.get('redirect_url') != null)
                                    ts.Redirect_Url__c = String.valueOf(temp.get('redirect_url'));
                                if(temp.get('cohort_id') != null)
                                    ts.Cohort_Id__c = String.valueOf(temp.get('cohort_id'));
                                if(temp.get('cohort_name') != null)
                                    ts.Cohort_Name__c = String.valueOf(temp.get('cohort_name'));
                                if(temp.get('tier_info') != null)
                                    ts.Tier_Info__c = String.valueOf(temp.get('tier_info'));
                                
                                if(leadOwnerIdByLearnerUID.containsKey(String.valueOf(temp.get('search_by_value'))))
                                    ts.OwnerId = leadOwnerIdByLearnerUID.get(String.valueOf(temp.get('search_by_value')));
                                    ts.Status = 'Completed';
                                activitylisttobeInsert.add(ts);
                            }
                        }
    
                        System.debug('ActivitylistTobeinsert::'+activityListTobeInsert);
                        if(!activityListTobeInsert.isEmpty()){
                            responseData.success_activity = new list<task>();
                            //responseData.failed_activity = new list<task>();
                            responseData.failed_activity_list = new list<ActivityModel.failuredata>();
                            Database.saveResult[] results =  database.Insert(activityListTobeInsert,false);
                            for(Integer index = 0, size = results.size(); index < size; index++){
                                if(results[index].isSuccess()){
                                    responseData.success_activity.add(activityListTobeInsert[index]);
                                }else{
                                    list<Database.Error> err = results[index].getErrors(); 
                                    ActivityModel.failuredata error = new ActivityModel.failuredata();
                                    system.debug('errerrerr::'+err);
                                    //responseData.failed_activity.add(activityListTobeInsert[index]);
                                    error.failed_activity = activityListTobeInsert[index];
                                    error.error_reason = err[0].getMessage();
                                    failureList.add(error);
                                }
                            }
                        }
                        //ob = activityWithoutLeadRec;
                        system.debug('activityWithoutLeadRec::'+activityWithoutLeadRec);
                        if(!failureList.isEmpty()){
                            responseData.failed_activity_list = failureList;
                        }
                        responseData.activity_without_lead = JSON.serialize(activityWithoutLeadRec);
                        responseData.success_code = '200';
                        //responseData.success_message = 'Activity record has been created.';
                
        }catch(Exception e){
            system.debug('Exception::'+e.getStackTraceString()+'---'+e.getMessage());
            responseData.error_code = '400';
            responseData.error_message = e.getStackTraceString();
            
        }
        return responseData;
    }
    
}